#!/usr/bin/env python3
"""Generate mathematical fixtures outside Elm JavaScript's exact range."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'morphir-scheme' / 'backend' / 'sdk_exact_integer_wbtest.mbt'
A = 9007199254740993
B = 4294967297
I64_MIN = -(2**63)
I64_MAX = 2**63 - 1


def case(name, source, expected):
    return {"fqName": name, "schemeExpression": source, "expected": expected}


def main():
    cases = [
        case('morphir/SDK:basics#add', f'(%morphir-sdk "morphir/SDK:basics#add" {A} 2)', str(A + 2)),
        case('morphir/SDK:basics#multiply', f'(%morphir-sdk "morphir/SDK:basics#multiply" {B} {B})', str(B * B)),
        case('morphir/SDK:basics#power', '(%morphir-sdk "morphir/SDK:basics#power" 2 100)', str(2**100)),
        case('morphir/SDK:basics#integer-divide', f'(%morphir-sdk "morphir/SDK:basics#integer-divide" {-A} 3)', str(-(A // 3))),
        case('morphir/SDK:basics#remainder-by', f'(%morphir-sdk "morphir/SDK:basics#remainder-by" 7 {-A})', str(-A - (-(A // 7)) * 7)),
        case('morphir/SDK:basics#mod-by', f'(%morphir-sdk "morphir/SDK:basics#mod-by" 7 {-A})', str(-A % 7)),
        case('morphir/SDK:string#from-int', f'(%morphir-sdk "morphir/SDK:string#from-int" {A})', json.dumps(str(A))),
        case('morphir/SDK:string#to-int', f'(%morphir-sdk "morphir/SDK:string#to-int" "{A}")', f'Just {A}'),
        case('morphir/SDK:list#range', f'(%morphir-sdk "morphir/SDK:list#range" {A} {A+2})', f'[{A},{A+1},{A+2}]'),
        case('morphir/SDK:decimal#from-int', f'(%morphir-sdk "morphir/SDK:decimal#from-int" {A})', json.dumps(str(A))),
        case('morphir/SDK:int#to-int64', f'(%morphir-sdk "morphir/SDK:int#to-int64" {I64_MIN})', f'Just {I64_MIN}'),
        case('morphir/SDK:int#to-int64', f'(%morphir-sdk "morphir/SDK:int#to-int64" {I64_MAX})', f'Just {I64_MAX}'),
        case('morphir/SDK:int#to-int64', f'(%morphir-sdk "morphir/SDK:int#to-int64" {I64_MAX+1})', 'Nothing'),
        case('morphir/SDK:int#from-int64', f'(%morphir-sdk "morphir/SDK:int#from-int64" (%morphir-tag "morphir/SDK:int#int64" {I64_MIN}))', str(I64_MIN)),
    ]
    destination = HERE / 'exact_integer_extension.json'
    destination.write_text(json.dumps({
        "classification": "approved exact-integer extension; not Elm oracle output",
        "authority": "Python 3 arbitrary-precision integer arithmetic and signed 64-bit bounds",
        "cases": cases,
    }, indent=2) + '\n')
    lines = ['// Generated by pkgs/morphir-sdk/conformance/generate_exact_integer_extension.py.',
             '// Mathematical extension beyond Elm JavaScript safe integers.', '', '///|',
             'test "exact integer extension beyond Elm safe range" {',
             '  let runtime = @scheme.Runtime::new()', '  install(runtime)',
             '  let cases : Array[(String, String, String)] = [']
    for item in cases:
        lines.append('    (' + ', '.join(json.dumps(item[key], ensure_ascii=False) for key in ('fqName','schemeExpression','expected')) + '),')
    lines += ['  ]', f'  assert_eq(cases.length(), {len(cases)})',
              '  for (name, source, expected) in cases {',
              '    let actual = oracle_render(runtime.eval(source), 0)',
              '    if actual != expected { abort(name + " expected " + expected + ", got " + actual) }',
              '  }', '}', '']
    OUT.write_text('\n'.join(lines))
    print(f'Wrote {len(cases)} exact extension cases')


if __name__ == '__main__':
    main()
