#!/usr/bin/env python3
"""Generate the Scheme backend's canonical SDK name and arity table."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INVENTORY = Path(__file__).with_name("bindings.json")
OUTPUT = ROOT / "morphir-scheme" / "backend" / "sdk_registry.mbt"


def main():
    values = json.loads(INVENTORY.read_text())["values"]
    if len(values) != 248:
        raise ValueError(f"expected 248 SDK values, found {len(values)}")
    lines = [
        "// Generated by pkgs/morphir-sdk/conformance/generate_scheme_registry.py.",
        "// Source: finos/morphir-elm bc99af69a8b24d391311fae3822a87eafef3c334.",
        "",
        "///|",
        "fn sdk_registry() -> Array[(String, Int)] {",
        "  [",
    ]
    seen = set()
    for value in values:
        name = value["fqName"]
        if name in seen:
            raise ValueError(f"duplicate SDK value: {name}")
        seen.add(name)
        arity = len(re.findall(r'\(\s*"[A-Za-z][A-Za-z0-9]*"\s*,', value["specification"]))
        lines.append(f'    ("{name}", {arity}),')
    lines += ["  ]", "}", "", "///|", "fn sdk_expected_arity(name : String) -> Int? {", "  match name {"]
    for value in values:
        name = value["fqName"]
        arity = len(re.findall(r'\(\s*"[A-Za-z][A-Za-z0-9]*"\s*,', value["specification"]))
        lines.append(f'    "{name}" => Some({arity})')
    lines += ["    _ => None", "  }", "}", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"Wrote {len(values)} SDK names to {OUTPUT}")


if __name__ == "__main__":
    main()
