#!/usr/bin/env python3
"""Embed the pinned Elm corpus and matching Scheme calls in MoonBit tests."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'morphir-scheme' / 'backend' / 'sdk_oracle_wbtest.mbt'


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def main():
    fixture = json.loads((HERE / 'elm_oracle.json').read_text())
    lines = ['// Generated by pkgs/morphir-sdk/conformance/generate_moonbit_oracle_tests.py.',
             '// Source: finos/morphir-elm bc99af69a8b24d391311fae3822a87eafef3c334.',
             '', '///|', 'test "pinned Elm SDK oracle examples" {',
             '  let runtime = @scheme.Runtime::new()', '  install(runtime)',
             '  let cases : Array[(String, String, String)] = [']
    count = 0
    for case in fixture['cases']:
        name = case['fqName']
        module, local = name.split(':', 1)[1].split('#')
        scheme = case['schemeExpression']
        if case['executed'] != (scheme is not None):
            raise ValueError(f'oracle and Scheme disagree on executability: {name}')
        if scheme is None:
            continue
        lines.append(f'    ({quote(name)}, {quote(scheme)}, {quote(case["elmDebug"])}),')
        count += 1
    lines += ['  ]', f'  assert_eq(cases.length(), {count})',
              '  for (name, source, expected) in cases {',
              '    let actual = try { oracle_render(runtime.eval(source), 0) } catch { _ => abort(name + " failed") }',
              '    if actual != expected {',
              '      abort(name + " expected " + expected + ", got " + actual)',
              '    }', '  }', '}', '']
    OUT.write_text('\n'.join(lines))
    print(f'Wrote {count} executable cases to {OUT}')


if __name__ == '__main__':
    main()
