"""Boundary examples executed by both the pinned Elm oracle and Scheme SDK."""

# (module, value, case label, Elm expression, Scheme expression)
BOUNDARIES = [
    ('basics','integer-divide','negative-divisor','-7 // -3','(%morphir-sdk "morphir/SDK:basics#integer-divide" -7 -3)'),
    ('basics','mod-by','negative-divisor','Basics.modBy -3 -7','(%morphir-sdk "morphir/SDK:basics#mod-by" -3 -7)'),
    ('basics','remainder-by','zero-dividend','Basics.remainderBy 3 0','(%morphir-sdk "morphir/SDK:basics#remainder-by" 3 0)'),
    ('basics','power','zero-exponent','2 ^ 0','(%morphir-sdk "morphir/SDK:basics#power" 2 0)'),
    ('basics','divide','infinity','1.0 / 0.0','(%morphir-sdk "morphir/SDK:basics#divide" 1.0 0.0)'),
    ('basics','divide','nan','0.0 / 0.0','(%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0)'),
    ('basics','sqrt','negative','Basics.sqrt -1.0','(%morphir-sdk "morphir/SDK:basics#sqrt" -1.0)'),
    ('basics','round','positive-half','Basics.round 2.5','(%morphir-sdk "morphir/SDK:basics#round" 2.5)'),
    ('basics','round','negative-half','Basics.round -3.5','(%morphir-sdk "morphir/SDK:basics#round" -3.5)'),
    ('basics','compare','utf16','Basics.compare "😀" "\uE000"','(%morphir-sdk "morphir/SDK:basics#compare" "😀" "\uE000")'),
    ('basics','equal','nested','[ (1, Just 2) ] == [ (1, Just 2) ]','(%morphir-sdk "morphir/SDK:basics#equal" (list (vector 1 (%morphir-tag "morphir/SDK:maybe#just" 2))) (list (vector 1 (%morphir-tag "morphir/SDK:maybe#just" 2))))'),
    ('basics','equal','nan','(0.0 / 0.0) == (0.0 / 0.0)','(%morphir-sdk "morphir/SDK:basics#equal" (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0) (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0))'),
    ('basics','not-equal','nan','(0.0 / 0.0) /= (0.0 / 0.0)','(%morphir-sdk "morphir/SDK:basics#not-equal" (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0) (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0))'),
    ('string','is-empty','nonempty','S.isEmpty "a"','(%morphir-sdk "morphir/SDK:string#is-empty" "a")'),
    ('string','slice','negative-index','S.slice -3 -1 "abcd"','(%morphir-sdk "morphir/SDK:string#slice" -3 -1 "abcd")'),
    ('string','split','empty-separator','S.split "" "ab"','(%morphir-sdk "morphir/SDK:string#split" "" "ab")'),
    ('string','indexes','overlap','S.indexes "aa" "aaaa"','(%morphir-sdk "morphir/SDK:string#indexes" "aa" "aaaa")'),
    ('string','uncons','supplementary','S.uncons "😀x"','(%morphir-sdk "morphir/SDK:string#uncons" "😀x")'),
    ('string','to-upper','case-expansion','S.toUpper "straße"','(%morphir-sdk "morphir/SDK:string#to-upper" "straße")'),
    ('string','to-int','invalid','S.toInt "12x"','(%morphir-sdk "morphir/SDK:string#to-int" "12x")'),
    ('string','to-float','invalid','S.toFloat "nan"','(%morphir-sdk "morphir/SDK:string#to-float" "nan")'),
    ('string','from-float','whole','S.fromFloat 7.0','(%morphir-sdk "morphir/SDK:string#from-float" 7.0)'),
    ('string','from-float','infinity','S.fromFloat (1.0 / 0.0)','(%morphir-sdk "morphir/SDK:string#from-float" (%morphir-sdk "morphir/SDK:basics#divide" 1.0 0.0))'),
    ('string','from-float','nan','S.fromFloat (0.0 / 0.0)','(%morphir-sdk "morphir/SDK:string#from-float" (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0))'),
    ('string','trim','unicode-space','S.trim "\u00A0x\u00A0"','(%morphir-sdk "morphir/SDK:string#trim" "\u00A0x\u00A0")'),
    ('list','head','empty','L.head []','(%morphir-sdk "morphir/SDK:list#head" (list))'),
    ('list','tail','empty','L.tail []','(%morphir-sdk "morphir/SDK:list#tail" (list))'),
    ('list','maximum','empty','L.maximum []','(%morphir-sdk "morphir/SDK:list#maximum" (list))'),
    ('list','minimum','empty','L.minimum []','(%morphir-sdk "morphir/SDK:list#minimum" (list))'),
    ('list','map2','shortest','L.map2 (+) [1, 2, 3] [4]','(%morphir-sdk "morphir/SDK:list#map2" (lambda (a) (lambda (b) (+ a b))) (list 1 2 3) (list 4))'),
    ('list','sort','duplicate','L.sort [2, 1, 2]','(%morphir-sdk "morphir/SDK:list#sort" (list 2 1 2))'),
    ('list','range','empty','L.range 2 1','(%morphir-sdk "morphir/SDK:list#range" 2 1)'),
    ('list','member','nan','L.member (0.0 / 0.0) [0.0 / 0.0]','(%morphir-sdk "morphir/SDK:list#member" (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0) (list (%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0)))'),
    ('list','take','negative','L.take -1 [1, 2]','(%morphir-sdk "morphir/SDK:list#take" -1 (list 1 2))'),
    ('maybe','map','nothing','M.map ((+) 1) Nothing','(%morphir-sdk "morphir/SDK:maybe#map" (lambda (x) (+ x 1)) (%morphir-tag "morphir/SDK:maybe#nothing"))'),
    ('maybe','map2','nothing','M.map2 (+) (Just 1) Nothing','(%morphir-sdk "morphir/SDK:maybe#map2" (lambda (a) (lambda (b) (+ a b))) (%morphir-tag "morphir/SDK:maybe#just" 1) (%morphir-tag "morphir/SDK:maybe#nothing"))'),
    ('maybe','has-value','nothing','MM.hasValue Nothing','(%morphir-sdk "morphir/SDK:maybe#has-value" (%morphir-tag "morphir/SDK:maybe#nothing"))'),
    ('result','map','error','R.map ((+) 1) (Err "bad")','(%morphir-sdk "morphir/SDK:result#map" (lambda (x) (+ x 1)) (%morphir-tag "morphir/SDK:result#err" "bad"))'),
    ('result','map2','first-error','R.map2 (+) (Err "first") (Err "second")','(%morphir-sdk "morphir/SDK:result#map2" (lambda (a) (lambda (b) (+ a b))) (%morphir-tag "morphir/SDK:result#err" "first") (%morphir-tag "morphir/SDK:result#err" "second"))'),
    ('result','to-maybe','error','R.toMaybe (Err "bad")','(%morphir-sdk "morphir/SDK:result#to-maybe" (%morphir-tag "morphir/SDK:result#err" "bad"))'),
    ('dict','from-list','duplicate-key','Dict.fromList [(1, 10), (1, 20)]','(%morphir-sdk "morphir/SDK:dict#from-list" (list (vector 1 10) (vector 1 20)))'),
    ('dict','get','missing','Dict.get 2 (Dict.singleton 1 10)','(%morphir-sdk "morphir/SDK:dict#get" 2 (%morphir-sdk "morphir/SDK:dict#singleton" 1 10))'),
    ('dict','foldl','empty','Dict.foldl (\\k v acc -> acc + v) 0 Dict.empty','(%morphir-sdk "morphir/SDK:dict#foldl" (lambda (k) (lambda (v) (lambda (acc) (+ acc v)))) 0 (%morphir-sdk "morphir/SDK:dict#empty"))'),
    ('dict','union','disjoint','Dict.union (Dict.singleton 2 20) (Dict.singleton 1 10)','(%morphir-sdk "morphir/SDK:dict#union" (%morphir-sdk "morphir/SDK:dict#singleton" 2 20) (%morphir-sdk "morphir/SDK:dict#singleton" 1 10))'),
    ('set','from-list','duplicate','Set.fromList [2, 1, 2]','(%morphir-sdk "morphir/SDK:set#from-list" (list 2 1 2))'),
    ('set','member','missing','Set.member 3 (Set.fromList [1, 2])','(%morphir-sdk "morphir/SDK:set#member" 3 (%morphir-sdk "morphir/SDK:set#from-list" (list 1 2)))'),
    ('set','foldr','empty','Set.foldr (\\v acc -> v + acc) 0 Set.empty','(%morphir-sdk "morphir/SDK:set#foldr" (lambda (v) (lambda (acc) (+ v acc))) 0 (%morphir-sdk "morphir/SDK:set#empty"))'),
    ('set','intersect','disjoint','Set.intersect (Set.singleton 1) (Set.singleton 2)','(%morphir-sdk "morphir/SDK:set#intersect" (%morphir-sdk "morphir/SDK:set#singleton" 1) (%morphir-sdk "morphir/SDK:set#singleton" 2))'),
    ('char','is-alpha','non-ascii','C.isAlpha \'é\'','(%morphir-sdk "morphir/SDK:char#is-alpha" #\\é)'),
    ('char','from-code','supplementary','C.fromCode 128512','(%morphir-sdk "morphir/SDK:char#from-code" 128512)'),
    ('char','to-upper','case-expansion','C.toUpper \'ß\'','(%morphir-sdk "morphir/SDK:char#to-upper" #\\ß)'),
    ('int','to-int8','overflow','I.toInt8 128','(%morphir-sdk "morphir/SDK:int#to-int8" 128)'),
    ('int','to-int16','lower-bound','I.toInt16 -32768','(%morphir-sdk "morphir/SDK:int#to-int16" -32768)'),
    ('int','to-int32','overflow','I.toInt32 2147483648','(%morphir-sdk "morphir/SDK:int#to-int32" 2147483648)'),
    ('decimal','from-string','scientific','D.fromString "1.25e2"','(%morphir-sdk "morphir/SDK:decimal#from-string" "1.25e2")'),
    ('decimal','from-string','invalid','D.fromString "bad"','(%morphir-sdk "morphir/SDK:decimal#from-string" "bad")'),
    ('decimal','div','zero-divisor','D.div (D.fromInt 1) (D.fromInt 0)','(%morphir-sdk "morphir/SDK:decimal#div" 1 0)'),
    ('decimal','round','negative-half','D.round (decimal "-2.5")','(%morphir-sdk "morphir/SDK:decimal#round" (%morphir-tag "decimal" "-2.5"))'),
    ('decimal','truncate','negative','D.truncate (decimal "-2.9")','(%morphir-sdk "morphir/SDK:decimal#truncate" (%morphir-tag "decimal" "-2.9"))'),
    ('decimal','eq','different-scale','D.eq (decimal "2.0") (D.fromInt 2)','(%morphir-sdk "morphir/SDK:decimal#eq" (%morphir-tag "decimal" "2.0") 2)'),
    ('decimal','from-float','decimal-fraction','D.fromFloat 0.1','(%morphir-sdk "morphir/SDK:decimal#from-float" 0.1)'),
]
