"""Scheme arguments for the matching pinned Elm oracle examples.

The call uses %morphir-sdk with its canonical FQName. Higher-order arguments
are curried Scheme lambdas, just as IR lambdas are after Scheme lowering.
"""

JUST = '(%morphir-tag "morphir/SDK:maybe#just" 2)'
NOTHING = '(%morphir-tag "morphir/SDK:maybe#nothing")'
OK = '(%morphir-tag "morphir/SDK:result#ok" 2)'
INC = '(lambda (x) (+ x 1))'
ADD2 = '(lambda (a) (lambda (b) (+ a b)))'
ADD3 = '(lambda (a) (lambda (b) (lambda (c) (+ a b c))))'
ADD4 = '(lambda (a) (lambda (b) (lambda (c) (lambda (d) (+ a b c d)))))'
ADD5 = '(lambda (a) (lambda (b) (lambda (c) (lambda (d) (lambda (e) (+ a b c d e))))))'
D12 = '(%morphir-sdk "morphir/SDK:decimal#from-string" "12.50")'

ARGS = {
    'basics': {
        'add': ['7','3'], 'subtract': ['7','3'], 'multiply': ['7','3'],
        'divide': ['7.0','2.0'], 'integer-divide': ['-7','3'], 'power': ['2','5'],
        'to-float': ['7'], 'round': ['-2.5'], 'floor': ['-2.5'],
        'ceiling': ['-2.5'], 'truncate': ['-2.5'],
        'mod-by': ['3','-7'], 'remainder-by': ['3','-7'],
        'negate': ['-7'], 'abs': ['-7'], 'clamp': ['1','5','8'],
        'is-na-n': ['(%morphir-sdk "morphir/SDK:basics#divide" 0.0 0.0)'],
        'is-infinite': ['(%morphir-sdk "morphir/SDK:basics#divide" 1.0 0.0)'],
        'sqrt': ['9.0'], 'log-base': ['2.0','8.0'],
        'e': [], 'pi': [], 'cos': ['0.0'], 'sin': ['0.0'],
        'tan': ['0.0'], 'acos': ['1.0'], 'asin': ['0.0'],
        'atan': ['0.0'], 'atan2': ['1.0','0.0'],
        'degrees': ['180.0'], 'radians': ['1.0'], 'turns': ['0.5'],
        'to-polar': ['#(3.0 4.0)'], 'from-polar': ['#(5.0 0.0)'],
        'equal': ["'(1 2)","'(1 2)"], 'not-equal': ['1','2'],
        'less-than': ['1','2'], 'greater-than': ['2','1'],
        'less-than-or-equal': ['2','2'], 'greater-than-or-equal': ['2','2'],
        'max': ['1','2'], 'min': ['1','2'], 'compare': ['1','2'],
        'not': ['#t'], 'and': ['#t','#f'], 'or': ['#t','#f'],
        'xor': ['#t','#f'], 'append': ['"a"','"b"'],
        'identity': ['42'], 'always': ['42','99'],
        'compose-left': ['(lambda (x) (+ x 1))','(lambda (x) (* x 2))'],
        'compose-right': ['(lambda (x) (+ x 1))','(lambda (x) (* x 2))'],
        'never': None,
    },
    'string': {
        'is-empty': ['""'], 'length': ['"a😀"'],
        'reverse': ['"ab😀"'], 'repeat': ['3','"ab"'],
        'replace': ['"a"','"x"','"banana"'],
        'append': ['"a"','"b"'], 'concat': ["'(\"a\" \"b\")"],
        'split': ['"-"','"a-b-c"'], 'join': ['"-"',"'(\"a\" \"b\")"],
        'words': ['" a  b "'], 'lines': ['"a\\nb"'],
        'slice': ['1','3','"abcd"'], 'left': ['2','"abcd"'],
        'right': ['2','"abcd"'], 'drop-left': ['2','"abcd"'],
        'drop-right': ['2','"abcd"'],
        'contains': ['"bc"','"abcd"'], 'starts-with': ['"ab"','"abcd"'],
        'ends-with': ['"cd"','"abcd"'],
        'indexes': ['"ab"','"abxab"'], 'indices': ['"ab"','"abxab"'],
        'to-int': ['"-42"'], 'from-int': ['-42'],
        'to-float': ['"3.5"'], 'from-float': ['3.5'],
        'from-char': ['#\\a'], 'cons': ['#\\a','"bc"'],
        'uncons': ['"abc"'], 'to-list': ['"abc"'],
        'from-list': ["'(#\\a #\\b)"], 'to-upper': ['"abc"'],
        'to-lower': ['"ABC"'], 'pad': ['5','#\\.','"a"'],
        'pad-left': ['5','#\\.','"a"'], 'pad-right': ['5','#\\.','"a"'],
        'trim': ['" a "'], 'trim-left': ['" a "'], 'trim-right': ['" a "'],
        'map': ['(lambda (c) (%morphir-sdk "morphir/SDK:char#to-upper" c))','"ab"'],
        'filter': ['(lambda (c) (%morphir-sdk "morphir/SDK:char#is-digit" c))','"a1b2"'],
        'foldl': ['(lambda (c) (lambda (n) (+ n (%morphir-sdk "morphir/SDK:char#to-code" c))))','0','"ab"'],
        'foldr': ['(lambda (c) (lambda (acc) (%morphir-sdk "morphir/SDK:string#cons" c acc)))','""','"ab"'],
        'any': ['(lambda (c) (%morphir-sdk "morphir/SDK:char#is-digit" c))','"a1"'],
        'all': ['(lambda (c) (%morphir-sdk "morphir/SDK:char#is-digit" c))','"12"'],
    },
    'list': {
        'singleton': ['3'], 'repeat': ['3','4'], 'range': ['-2','2'],
        'cons': ['1',"'(2 3)"], 'map': [INC,"'(1 2)"],
        'indexed-map': ['(lambda (i) (lambda (v) (+ i v)))',"'(10 20)"],
        'foldl': ['(lambda (v) (lambda (acc) (- v acc)))','0',"'(1 2 3)"],
        'foldr': ['(lambda (v) (lambda (acc) (- v acc)))','0',"'(1 2 3)"],
        'filter': ['(lambda (v) (> v 1))',"'(1 2 3)"],
        'filter-map': ['(lambda (v) (if (> v 1) (%morphir-tag "morphir/SDK:maybe#just" v) (%morphir-tag "morphir/SDK:maybe#nothing")))',"'(1 2 3)"],
        'length': ["'(1 2 3)"], 'reverse': ["'(1 2 3)"],
        'member': ['2',"'(1 2 3)"], 'all': ['(lambda (v) (> v 0))',"'(1 2)"],
        'any': ['(lambda (v) (> v 2))',"'(1 2 3)"],
        'maximum': ["'(1 3 2)"], 'minimum': ["'(1 3 2)"],
        'sum': ["'(1 2 3)"], 'product': ["'(2 3 4)"],
        'append': ["'(1 2)","'(3)"], 'concat': ["'((1) (2 3))"],
        'concat-map': ['(lambda (v) (list v v))',"'(1 2)"],
        'intersperse': ['0',"'(1 2 3)"],
        'map2': [ADD2,"'(1 2)","'(3 4)"],
        'map3': [ADD3,"'(1)","'(2)","'(3)"],
        'map4': [ADD4,"'(1)","'(2)","'(3)","'(4)"],
        'map5': [ADD5,"'(1)","'(2)","'(3)","'(4)","'(5)"],
        'sort': ["'(3 1 2)"],
        'sort-by': ['(lambda (pair) (vector-ref pair 0))',"'(#(2 \"b\") #(1 \"a\"))"],
        'sort-with': ['(lambda (a) (lambda (b) (%morphir-sdk "morphir/SDK:basics#compare" b a)))',"'(1 3 2)"],
        'is-empty': ["'()"], 'head': ["'(1 2)"], 'tail': ["'(1 2)"],
        'take': ['2',"'(1 2 3)"], 'drop': ['2',"'(1 2 3)"],
        'partition': ['(lambda (v) (> v 1))',"'(1 2 3)"],
        'unzip': ["'(#(1 2) #(3 4))"],
        'inner-join': ["'(2 3)",'(lambda (a) (lambda (b) (= a b)))',"'(1 2)"],
        'left-join': ["'(2 3)",'(lambda (a) (lambda (b) (= a b)))',"'(1 2)"],
    },
    'maybe': {
        'and-then': ['(lambda (v) (%morphir-tag "morphir/SDK:maybe#just" (+ v 1)))',JUST],
        'map': [INC,JUST],
        'map2': [ADD2,'(%morphir-tag "morphir/SDK:maybe#just" 1)',JUST],
        'map3': [ADD3,'(%morphir-tag "morphir/SDK:maybe#just" 1)',JUST,'(%morphir-tag "morphir/SDK:maybe#just" 3)'],
        'map4': [ADD4,'(%morphir-tag "morphir/SDK:maybe#just" 1)',JUST,'(%morphir-tag "morphir/SDK:maybe#just" 3)','(%morphir-tag "morphir/SDK:maybe#just" 4)'],
        'map5': [ADD5,'(%morphir-tag "morphir/SDK:maybe#just" 1)',JUST,'(%morphir-tag "morphir/SDK:maybe#just" 3)','(%morphir-tag "morphir/SDK:maybe#just" 4)','(%morphir-tag "morphir/SDK:maybe#just" 5)'],
        'with-default': ['9',NOTHING], 'has-value': ['(%morphir-tag "morphir/SDK:maybe#just" 1)'],
    },
    'result': {
        'and-then': ['(lambda (v) (%morphir-tag "morphir/SDK:result#ok" (+ v 1)))',OK],
        'map': [INC,OK],
        'map2': [ADD2,'(%morphir-tag "morphir/SDK:result#ok" 1)',OK],
        'map3': [ADD3,'(%morphir-tag "morphir/SDK:result#ok" 1)',OK,'(%morphir-tag "morphir/SDK:result#ok" 3)'],
        'map4': [ADD4,'(%morphir-tag "morphir/SDK:result#ok" 1)',OK,'(%morphir-tag "morphir/SDK:result#ok" 3)','(%morphir-tag "morphir/SDK:result#ok" 4)'],
        'map5': [ADD5,'(%morphir-tag "morphir/SDK:result#ok" 1)',OK,'(%morphir-tag "morphir/SDK:result#ok" 3)','(%morphir-tag "morphir/SDK:result#ok" 4)','(%morphir-tag "morphir/SDK:result#ok" 5)'],
        'with-default': ['9','(%morphir-tag "morphir/SDK:result#err" "bad")'],
        'to-maybe': [OK], 'from-maybe': ['"bad"',JUST],
        'map-error': ['(lambda (text) (%morphir-sdk "morphir/SDK:string#length" text))','(%morphir-tag "morphir/SDK:result#err" "bad")'],
    },
    'dict': {
        'empty': [], 'singleton': ['2','20'],
        'insert': ['2','20','(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)'],
        'update': ['2','(lambda (old) (%morphir-tag "morphir/SDK:maybe#just" 22))','(%morphir-sdk "morphir/SDK:dict#singleton" 2 20)'],
        'remove': ['1','(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(1 10) #(2 20)))'],
        'is-empty': ['(%morphir-sdk "morphir/SDK:dict#empty")'],
        'member': ['1','(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)'],
        'get': ['1','(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)'],
        'size': ['(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)'],
        'keys': ['(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(2 20) #(1 10)))'],
        'values': ['(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(2 20) #(1 10)))'],
        'to-list': ['(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(2 20) #(1 10)))'],
        'from-list': ["'(#(2 20) #(1 10))"],
        'map': ['(lambda (k) (lambda (v) (+ k v)))','(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)'],
        'foldl': ['(lambda (k) (lambda (v) (lambda (acc) (append acc (list (vector k v))))))',"'()",'(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(2 20) #(1 10)))'],
        'foldr': ['(lambda (k) (lambda (v) (lambda (acc) (append acc (list (vector k v))))))',"'()",'(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(2 20) #(1 10)))'],
        'filter': ['(lambda (k) (lambda (v) (> k 1)))','(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(1 10) #(2 20)))'],
        'partition': ['(lambda (k) (lambda (v) (> k 1)))','(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(1 10) #(2 20)))'],
        'union': ['(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)','(%morphir-sdk "morphir/SDK:dict#singleton" 1 99)'],
        'intersect': ['(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(1 10) #(2 20)))','(%morphir-sdk "morphir/SDK:dict#singleton" 2 99)'],
        'diff': ['(%morphir-sdk "morphir/SDK:dict#from-list" \'(#(1 10) #(2 20)))','(%morphir-sdk "morphir/SDK:dict#singleton" 2 99)'],
        'merge': [
          '(lambda (k) (lambda (v) (lambda (acc) (append acc (list (vector k v))))))',
          '(lambda (k) (lambda (a) (lambda (b) (lambda (acc) (append acc (list (vector k a)))))))',
          '(lambda (k) (lambda (v) (lambda (acc) (append acc (list (vector k v))))))',
          '(%morphir-sdk "morphir/SDK:dict#singleton" 1 10)',
          '(%morphir-sdk "morphir/SDK:dict#singleton" 2 20)',"'()"
        ],
    },
    'set': {
        'empty': [], 'singleton': ['2'],
        'insert': ['2','(%morphir-sdk "morphir/SDK:set#singleton" 1)'],
        'remove': ['1','(%morphir-sdk "morphir/SDK:set#from-list" \'(1 2))'],
        'is-empty': ['(%morphir-sdk "morphir/SDK:set#empty")'],
        'member': ['1','(%morphir-sdk "morphir/SDK:set#singleton" 1)'],
        'size': ['(%morphir-sdk "morphir/SDK:set#singleton" 1)'],
        'to-list': ['(%morphir-sdk "morphir/SDK:set#from-list" \'(2 1))'],
        'from-list': ["'(2 1)"],
        'map': [INC,'(%morphir-sdk "morphir/SDK:set#from-list" \'(1 2))'],
        'foldl': ['(lambda (v) (lambda (acc) (append acc (list v))))',"'()",'(%morphir-sdk "morphir/SDK:set#from-list" \'(2 1))'],
        'foldr': ['(lambda (v) (lambda (acc) (append acc (list v))))',"'()",'(%morphir-sdk "morphir/SDK:set#from-list" \'(2 1))'],
        'filter': ['(lambda (v) (> v 1))','(%morphir-sdk "morphir/SDK:set#from-list" \'(1 2))'],
        'partition': ['(lambda (v) (> v 1))','(%morphir-sdk "morphir/SDK:set#from-list" \'(1 2))'],
        'union': ['(%morphir-sdk "morphir/SDK:set#singleton" 1)','(%morphir-sdk "morphir/SDK:set#singleton" 2)'],
        'intersect': ['(%morphir-sdk "morphir/SDK:set#from-list" \'(1 2))','(%morphir-sdk "morphir/SDK:set#singleton" 2)'],
        'diff': ['(%morphir-sdk "morphir/SDK:set#from-list" \'(1 2))','(%morphir-sdk "morphir/SDK:set#singleton" 2)'],
    },
    'char': {
        'is-upper': ['#\\A'], 'is-lower': ['#\\a'],
        'is-alpha': ['#\\a'], 'is-alpha-num': ['#\\7'],
        'is-digit': ['#\\7'], 'is-oct-digit': ['#\\7'],
        'is-hex-digit': ['#\\F'], 'to-upper': ['#\\a'],
        'to-lower': ['#\\A'], 'to-locale-upper': ['#\\a'],
        'to-locale-lower': ['#\\A'], 'to-code': ['#\\A'],
        'from-code': ['65'],
    },
    'int': {
        'from-int8': ['(%morphir-tag "morphir/SDK:int#int8" 12)'],
        'to-int8': ['127'],
        'from-int16': ['(%morphir-tag "morphir/SDK:int#int16" 1234)'],
        'to-int16': ['32767'],
        'from-int32': ['(%morphir-tag "morphir/SDK:int#int32" 1234)'],
        'to-int32': ['2147483647'],
        'from-int64': None, 'to-int64': None,
    },
    'decimal': {
        'from-int': ['12'], 'from-float': ['1.25'],
        'from-string': ['"12.50"'], 'hundred': ['2'],
        'thousand': ['2'], 'million': ['2'], 'tenth': ['2'],
        'hundredth': ['2'], 'thousandth': ['2'], 'millionth': ['2'],
        'bps': ['2'], 'to-string': ['12'], 'to-float': ['12'],
        'add': ['2','3'], 'sub': ['2','3'], 'negate': ['2'],
        'mul': ['2','3'], 'div': ['1','3'],
        'div-with-default': ['99','1','0'],
        'truncate': ['(%morphir-tag "decimal" "-2.9")'],
        'round': ['(%morphir-tag "decimal" "2.5")'],
        'gt': ['2','1'], 'gte': ['2','2'], 'eq': ['2','2'],
        'neq': ['2','1'], 'lt': ['1','2'], 'lte': ['2','2'],
        'compare': ['1','2'], 'abs': ['-2'],
        'shift-decimal-left': ['2','123'],
        'shift-decimal-right': ['2','123'],
        'zero': [], 'one': [], 'minus-one': [],
    },
}


def expression(module, name):
    args = ARGS[module][name]
    if args is None:
        return None
    quoted = f'"morphir/SDK:{module}#{name}"'
    call = f'(%morphir-sdk {quoted}' + ('' if not args else ' ' + ' '.join(args)) + ')'
    if module == 'basics' and name in ('compose-left', 'compose-right'):
        return f'({call} 3)'
    return call
