"""Pinned Elm expressions for each executable Morphir SDK value.

Each expression is evaluated by Elm 0.19.1 against elm/core 1.0.5 and the
specified finos/morphir-elm checkout. Values with no possible inhabitant are
recorded as explicit non-executable cases.
"""

CASES = {
    "basics": {
        "add": "7 + 3", "subtract": "7 - 3", "multiply": "7 * 3",
        "divide": "7.0 / 2.0", "integer-divide": "-7 // 3", "power": "2 ^ 5",
        "to-float": "Basics.toFloat 7", "round": "Basics.round -2.5",
        "floor": "Basics.floor -2.5", "ceiling": "Basics.ceiling -2.5",
        "truncate": "Basics.truncate -2.5", "mod-by": "Basics.modBy 3 -7",
        "remainder-by": "Basics.remainderBy 3 -7", "negate": "Basics.negate -7",
        "abs": "Basics.abs -7", "clamp": "Basics.clamp 1 5 8",
        "is-na-n": "Basics.isNaN (0.0 / 0.0)",
        "is-infinite": "Basics.isInfinite (1.0 / 0.0)",
        "sqrt": "Basics.sqrt 9.0", "log-base": "Basics.logBase 2.0 8.0",
        "e": "Basics.e", "pi": "Basics.pi", "cos": "Basics.cos 0.0",
        "sin": "Basics.sin 0.0", "tan": "Basics.tan 0.0",
        "acos": "Basics.acos 1.0", "asin": "Basics.asin 0.0",
        "atan": "Basics.atan 0.0", "atan2": "Basics.atan2 1.0 0.0",
        "degrees": "Basics.degrees 180.0", "radians": "Basics.radians 1.0",
        "turns": "Basics.turns 0.5", "to-polar": "Basics.toPolar (3.0, 4.0)",
        "from-polar": "Basics.fromPolar (5.0, 0.0)",
        "equal": "[1, 2] == [1, 2]", "not-equal": "1 /= 2",
        "less-than": "1 < 2", "greater-than": "2 > 1",
        "less-than-or-equal": "2 <= 2", "greater-than-or-equal": "2 >= 2",
        "max": "Basics.max 1 2", "min": "Basics.min 1 2",
        "compare": "Basics.compare 1 2", "not": "Basics.not True",
        "and": "True && False", "or": "True || False",
        "xor": "Basics.xor True False", "append": "\"a\" ++ \"b\"",
        "identity": "Basics.identity 42", "always": "Basics.always 42 99",
        "compose-left": "((\\x -> x + 1) << (\\x -> x * 2)) 3",
        "compose-right": "((\\x -> x + 1) >> (\\x -> x * 2)) 3",
        "never": None,
    },
    "string": {
        "is-empty": "S.isEmpty \"\"", "length": "S.length \"a😀\"",
        "reverse": "S.reverse \"ab😀\"", "repeat": "S.repeat 3 \"ab\"",
        "replace": "S.replace \"a\" \"x\" \"banana\"",
        "append": "S.append \"a\" \"b\"", "concat": "S.concat [\"a\", \"b\"]",
        "split": "S.split \"-\" \"a-b-c\"", "join": "S.join \"-\" [\"a\", \"b\"]",
        "words": "S.words \" a  b \"", "lines": "S.lines \"a\\nb\"",
        "slice": "S.slice 1 3 \"abcd\"", "left": "S.left 2 \"abcd\"",
        "right": "S.right 2 \"abcd\"", "drop-left": "S.dropLeft 2 \"abcd\"",
        "drop-right": "S.dropRight 2 \"abcd\"",
        "contains": "S.contains \"bc\" \"abcd\"",
        "starts-with": "S.startsWith \"ab\" \"abcd\"",
        "ends-with": "S.endsWith \"cd\" \"abcd\"",
        "indexes": "S.indexes \"ab\" \"abxab\"",
        "indices": "S.indices \"ab\" \"abxab\"",
        "to-int": "S.toInt \"-42\"", "from-int": "S.fromInt -42",
        "to-float": "S.toFloat \"3.5\"", "from-float": "S.fromFloat 3.5",
        "from-char": "S.fromChar 'a'", "cons": "S.cons 'a' \"bc\"",
        "uncons": "S.uncons \"abc\"", "to-list": "S.toList \"abc\"",
        "from-list": "S.fromList ['a', 'b']", "to-upper": "S.toUpper \"abc\"",
        "to-lower": "S.toLower \"ABC\"", "pad": "S.pad 5 '.' \"a\"",
        "pad-left": "S.padLeft 5 '.' \"a\"",
        "pad-right": "S.padRight 5 '.' \"a\"",
        "trim": "S.trim \" a \"", "trim-left": "S.trimLeft \" a \"",
        "trim-right": "S.trimRight \" a \"",
        "map": "S.map C.toUpper \"ab\"",
        "filter": "S.filter C.isDigit \"a1b2\"",
        "foldl": "S.foldl (\\c n -> n + C.toCode c) 0 \"ab\"",
        "foldr": "S.foldr (\\c acc -> S.cons c acc) \"\" \"ab\"",
        "any": "S.any C.isDigit \"a1\"", "all": "S.all C.isDigit \"12\"",
    },
    "list": {
        "singleton": "L.singleton 3", "repeat": "L.repeat 3 4",
        "range": "L.range -2 2", "cons": "1 :: [2, 3]",
        "map": "L.map ((+) 1) [1, 2]",
        "indexed-map": "L.indexedMap (\\i v -> i + v) [10, 20]",
        "foldl": "L.foldl (\\v acc -> v - acc) 0 [1, 2, 3]",
        "foldr": "L.foldr (\\v acc -> v - acc) 0 [1, 2, 3]",
        "filter": "L.filter (\\v -> v > 1) [1, 2, 3]",
        "filter-map": "L.filterMap (\\v -> if v > 1 then Just v else Nothing) [1, 2, 3]",
        "length": "L.length [1, 2, 3]", "reverse": "L.reverse [1, 2, 3]",
        "member": "L.member 2 [1, 2, 3]", "all": "L.all (\\v -> v > 0) [1, 2]",
        "any": "L.any (\\v -> v > 2) [1, 2, 3]",
        "maximum": "L.maximum [1, 3, 2]", "minimum": "L.minimum [1, 3, 2]",
        "sum": "L.sum [1, 2, 3]", "product": "L.product [2, 3, 4]",
        "append": "L.append [1, 2] [3]", "concat": "L.concat [[1], [2, 3]]",
        "concat-map": "L.concatMap (\\v -> [v, v]) [1, 2]",
        "intersperse": "L.intersperse 0 [1, 2, 3]",
        "map2": "L.map2 (+) [1, 2] [3, 4]",
        "map3": "L.map3 (\\a b c -> a + b + c) [1] [2] [3]",
        "map4": "L.map4 (\\a b c d -> a + b + c + d) [1] [2] [3] [4]",
        "map5": "L.map5 (\\a b c d e -> a + b + c + d + e) [1] [2] [3] [4] [5]",
        "sort": "L.sort [3, 1, 2]", "sort-by": "L.sortBy Tuple.first [(2, \"b\"), (1, \"a\")]",
        "sort-with": "L.sortWith (\\a b -> Basics.compare b a) [1, 3, 2]",
        "is-empty": "L.isEmpty []", "head": "L.head [1, 2]",
        "tail": "L.tail [1, 2]", "take": "L.take 2 [1, 2, 3]",
        "drop": "L.drop 2 [1, 2, 3]",
        "partition": "L.partition (\\v -> v > 1) [1, 2, 3]",
        "unzip": "L.unzip [(1, 2), (3, 4)]",
        "inner-join": "ML.innerJoin [2, 3] (\\a b -> a == b) [1, 2]",
        "left-join": "ML.leftJoin [2, 3] (\\a b -> a == b) [1, 2]",
    },
    "maybe": {
        "and-then": "M.andThen (\\v -> Just (v + 1)) (Just 2)",
        "map": "M.map ((+) 1) (Just 2)",
        "map2": "M.map2 (+) (Just 1) (Just 2)",
        "map3": "M.map3 (\\a b c -> a + b + c) (Just 1) (Just 2) (Just 3)",
        "map4": "M.map4 (\\a b c d -> a + b + c + d) (Just 1) (Just 2) (Just 3) (Just 4)",
        "map5": "M.map5 (\\a b c d e -> a + b + c + d + e) (Just 1) (Just 2) (Just 3) (Just 4) (Just 5)",
        "with-default": "M.withDefault 9 Nothing",
        "has-value": "MM.hasValue (Just 1)",
    },
    "result": {
        "and-then": "R.andThen (\\v -> Ok (v + 1)) (Ok 2)",
        "map": "R.map ((+) 1) (Ok 2)",
        "map2": "R.map2 (+) (Ok 1) (Ok 2)",
        "map3": "R.map3 (\\a b c -> a + b + c) (Ok 1) (Ok 2) (Ok 3)",
        "map4": "R.map4 (\\a b c d -> a + b + c + d) (Ok 1) (Ok 2) (Ok 3) (Ok 4)",
        "map5": "R.map5 (\\a b c d e -> a + b + c + d + e) (Ok 1) (Ok 2) (Ok 3) (Ok 4) (Ok 5)",
        "with-default": "R.withDefault 9 (Err \"bad\")",
        "to-maybe": "R.toMaybe (Ok 2)",
        "from-maybe": "R.fromMaybe \"bad\" (Just 2)",
        "map-error": "R.mapError S.length (Err \"bad\")",
    },
    "dict": {
        "empty": "Dict.empty", "singleton": "Dict.singleton 2 20",
        "insert": "Dict.insert 2 20 (Dict.singleton 1 10)",
        "update": "Dict.update 2 (\\_ -> Just 22) (Dict.singleton 2 20)",
        "remove": "Dict.remove 1 (Dict.fromList [(1, 10), (2, 20)])",
        "is-empty": "Dict.isEmpty Dict.empty",
        "member": "Dict.member 1 (Dict.singleton 1 10)",
        "get": "Dict.get 1 (Dict.singleton 1 10)",
        "size": "Dict.size (Dict.singleton 1 10)",
        "keys": "Dict.keys (Dict.fromList [(2, 20), (1, 10)])",
        "values": "Dict.values (Dict.fromList [(2, 20), (1, 10)])",
        "to-list": "Dict.toList (Dict.fromList [(2, 20), (1, 10)])",
        "from-list": "Dict.fromList [(2, 20), (1, 10)]",
        "map": "Dict.map (\\k v -> k + v) (Dict.singleton 1 10)",
        "foldl": "Dict.foldl (\\k v acc -> acc ++ [(k, v)]) [] (Dict.fromList [(2, 20), (1, 10)])",
        "foldr": "Dict.foldr (\\k v acc -> acc ++ [(k, v)]) [] (Dict.fromList [(2, 20), (1, 10)])",
        "filter": "Dict.filter (\\k _ -> k > 1) (Dict.fromList [(1, 10), (2, 20)])",
        "partition": "Dict.partition (\\k _ -> k > 1) (Dict.fromList [(1, 10), (2, 20)])",
        "union": "Dict.union (Dict.singleton 1 10) (Dict.singleton 1 99)",
        "intersect": "Dict.intersect (Dict.fromList [(1, 10), (2, 20)]) (Dict.singleton 2 99)",
        "diff": "Dict.diff (Dict.fromList [(1, 10), (2, 20)]) (Dict.singleton 2 99)",
        "merge": "Dict.merge (\\k v acc -> acc ++ [(k, v)]) (\\k v _ acc -> acc ++ [(k, v)]) (\\k v acc -> acc ++ [(k, v)]) (Dict.singleton 1 10) (Dict.singleton 2 20) []",
    },
    "set": {
        "empty": "Set.empty", "singleton": "Set.singleton 2",
        "insert": "Set.insert 2 (Set.singleton 1)",
        "remove": "Set.remove 1 (Set.fromList [1, 2])",
        "is-empty": "Set.isEmpty Set.empty", "member": "Set.member 1 (Set.singleton 1)",
        "size": "Set.size (Set.singleton 1)",
        "to-list": "Set.toList (Set.fromList [2, 1])",
        "from-list": "Set.fromList [2, 1]",
        "map": "Set.map ((+) 1) (Set.fromList [1, 2])",
        "foldl": "Set.foldl (\\v acc -> acc ++ [v]) [] (Set.fromList [2, 1])",
        "foldr": "Set.foldr (\\v acc -> acc ++ [v]) [] (Set.fromList [2, 1])",
        "filter": "Set.filter (\\v -> v > 1) (Set.fromList [1, 2])",
        "partition": "Set.partition (\\v -> v > 1) (Set.fromList [1, 2])",
        "union": "Set.union (Set.singleton 1) (Set.singleton 2)",
        "intersect": "Set.intersect (Set.fromList [1, 2]) (Set.singleton 2)",
        "diff": "Set.diff (Set.fromList [1, 2]) (Set.singleton 2)",
    },
    "char": {
        "is-upper": "C.isUpper 'A'", "is-lower": "C.isLower 'a'",
        "is-alpha": "C.isAlpha 'a'", "is-alpha-num": "C.isAlphaNum '7'",
        "is-digit": "C.isDigit '7'", "is-oct-digit": "C.isOctDigit '7'",
        "is-hex-digit": "C.isHexDigit 'F'", "to-upper": "C.toUpper 'a'",
        "to-lower": "C.toLower 'A'", "to-locale-upper": "C.toLocaleUpper 'a'",
        "to-locale-lower": "C.toLocaleLower 'A'",
        "to-code": "C.toCode 'A'", "from-code": "C.fromCode 65",
    },
    "int": {
        "from-int8": "M.withDefault 0 (M.map I.fromInt8 (I.toInt8 12))",
        "to-int8": "I.toInt8 127",
        "from-int16": "M.withDefault 0 (M.map I.fromInt16 (I.toInt16 1234))",
        "to-int16": "I.toInt16 32767",
        "from-int32": "M.withDefault 0 (M.map I.fromInt32 (I.toInt32 1234))",
        "to-int32": "I.toInt32 2147483647",
        # The pinned Elm implementation compiles this bound as `--922...`,
        # which produces invalid JavaScript before a case can run.
        "from-int64": None,
        "to-int64": None,
    },
    "decimal": {
        "from-int": "D.fromInt 12", "from-float": "D.fromFloat 1.25",
        "from-string": "D.fromString \"12.50\"", "hundred": "D.hundred 2",
        "thousand": "D.thousand 2", "million": "D.million 2",
        "tenth": "D.tenth 2", "hundredth": "D.hundredth 2",
        "thousandth": "D.thousandth 2", "millionth": "D.millionth 2",
        "bps": "D.bps 2", "to-string": "D.toString (D.fromInt 12)",
        "to-float": "D.toFloat (D.fromInt 12)",
        "add": "D.add (D.fromInt 2) (D.fromInt 3)",
        "sub": "D.sub (D.fromInt 2) (D.fromInt 3)",
        "negate": "D.negate (D.fromInt 2)",
        "mul": "D.mul (D.fromInt 2) (D.fromInt 3)",
        "div": "D.div (D.fromInt 1) (D.fromInt 3)",
        "div-with-default": "D.divWithDefault (D.fromInt 99) (D.fromInt 1) (D.fromInt 0)",
        "truncate": "D.truncate (decimal \"-2.9\")",
        "round": "D.round (decimal \"2.5\")",
        "gt": "D.gt (D.fromInt 2) (D.fromInt 1)",
        "gte": "D.gte (D.fromInt 2) (D.fromInt 2)",
        "eq": "D.eq (D.fromInt 2) (D.fromInt 2)",
        "neq": "D.neq (D.fromInt 2) (D.fromInt 1)",
        "lt": "D.lt (D.fromInt 1) (D.fromInt 2)",
        "lte": "D.lte (D.fromInt 2) (D.fromInt 2)",
        "compare": "D.compare (D.fromInt 1) (D.fromInt 2)",
        "abs": "D.abs (D.fromInt -2)",
        "shift-decimal-left": "D.shiftDecimalLeft 2 (D.fromInt 123)",
        "shift-decimal-right": "D.shiftDecimalRight 2 (D.fromInt 123)",
        "zero": "D.zero", "one": "D.one", "minus-one": "D.minusOne",
    },
}
