#!/usr/bin/env python3
"""Write fixtures/classic_ir.mbt from the classic IR conformance fixtures.

The JSON comes from pkgs/morphir-ir/conformance/fixtures, which scripts/refresh-ir-fixtures.py vendors from
finos/morphir and finos/morphir-elm. Run this script again after a refresh.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3]
SOURCE = ROOT / "pkgs/morphir-ir/conformance/fixtures"
OUTPUT = ROOT / "pkgs/morphir-elm/fixtures/classic_ir.mbt"
FIXTURES = [
    ("classic_greeting_json", "v3-greeting.json"),
    ("classic_rentals_v1_json", "v1-rentals.json"),
    ("classic_rentals_v2_json", "v2-rentals.json"),
]


def main():
    lines = [
        "// GENERATED by pkgs/morphir-elm/scripts/embed-classic-fixtures.py. Do not edit.",
        "// Source: pkgs/morphir-ir/conformance/fixtures. Upstream JSON: FINOS, Apache-2.0.",
    ]
    for function, name in FIXTURES:
        source = json.loads((SOURCE / name).read_text())
        text = json.dumps(source, separators=(",", ":"))
        lines += ["", "///|", f"fn {function}() -> String {{", "  " + json.dumps(text), "}"]
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(FIXTURES)} fixtures to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
