#!/usr/bin/env python3
"""Write backend/mapping_builtin.mbt from the SDK binding inventory.

Only bindings whose semantics come from elm/core 1.0.5 map to Elm. Every other SDK reference stays qualified and
resolves through the finos/morphir-elm Elm package.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3]
BINDINGS = ROOT / "pkgs/morphir-sdk/conformance/bindings.json"
OUTPUT = ROOT / "pkgs/morphir-elm/backend/mapping_builtin.mbt"

# Elm modules that every Elm module imports by default.
DEFAULT_IMPORTS = {"Basics", "List", "Maybe", "Result", "String", "Char", "Tuple"}
ELM_MODULE = {
    "basics": "Basics", "list": "List", "maybe": "Maybe", "result": "Result", "string": "String",
    "char": "Char", "dict": "Dict", "set": "Set", "tuple": "Tuple",
}
OPERATORS = {
    "morphir/SDK:basics#add": "+", "morphir/SDK:basics#subtract": "-", "morphir/SDK:basics#multiply": "*",
    "morphir/SDK:basics#divide": "/", "morphir/SDK:basics#integer-divide": "//", "morphir/SDK:basics#power": "^",
    "morphir/SDK:basics#equal": "==", "morphir/SDK:basics#not-equal": "/=",
    "morphir/SDK:basics#less-than": "<", "morphir/SDK:basics#greater-than": ">",
    "morphir/SDK:basics#less-than-or-equal": "<=", "morphir/SDK:basics#greater-than-or-equal": ">=",
    "morphir/SDK:basics#and": "&&", "morphir/SDK:basics#or": "||", "morphir/SDK:basics#append": "++",
    "morphir/SDK:basics#compose-left": "<<", "morphir/SDK:basics#compose-right": ">>",
    "morphir/SDK:list#cons": "::",
}
# Types and constructors are not in the value inventory.
TYPES = {
    "morphir/SDK:basics#int": ("Int", None), "morphir/SDK:basics#float": ("Float", None),
    "morphir/SDK:basics#bool": ("Bool", None), "morphir/SDK:basics#order": ("Order", None),
    "morphir/SDK:basics#never": ("Never", None), "morphir/SDK:string#string": ("String", None),
    "morphir/SDK:char#char": ("Char", None), "morphir/SDK:list#list": ("List", None),
    "morphir/SDK:maybe#maybe": ("Maybe", None), "morphir/SDK:result#result": ("Result", None),
    "morphir/SDK:dict#dict": ("Dict.Dict", "Dict"), "morphir/SDK:set#set": ("Set.Set", "Set"),
}
CONSTRUCTORS = {
    "morphir/SDK:maybe#just": "Just", "morphir/SDK:maybe#nothing": "Nothing",
    "morphir/SDK:result#ok": "Ok", "morphir/SDK:result#err": "Err",
    "morphir/SDK:basics#lt": "LT", "morphir/SDK:basics#eq": "EQ", "morphir/SDK:basics#gt": "GT",
}


def text(value):
    return "None" if value is None else "Some(" + json.dumps(value) + ")"


def main():
    values = json.loads(BINDINGS.read_text())["values"]
    entries = []
    for key, (name, imp) in sorted(TYPES.items()):
        entries.append((key, f"Type({json.dumps(name)}, {text(imp)})"))
    for key, name in sorted(CONSTRUCTORS.items()):
        entries.append((key, f"Function({json.dumps(name)}, None)"))
    for binding in sorted(values, key=lambda b: b["fqName"]):
        key = binding["fqName"]
        if key in OPERATORS:
            entries.append((key, f"Operator({json.dumps(OPERATORS[key])})"))
            continue
        if binding["semanticSource"] != "elm/core 1.0.5":
            continue
        module = ELM_MODULE[key.split(":")[1].split("#")[0]]
        name = binding["elmName"] if module == "Basics" else module + "." + binding["elmName"]
        imp = None if module in DEFAULT_IMPORTS else module
        entries.append((key, f"Function({json.dumps(name)}, {text(imp)})"))
    lines = [
        "// GENERATED by pkgs/morphir-elm/scripts/generate-builtin-mapping.py. Do not edit.",
        "// Source: pkgs/morphir-sdk/conformance/bindings.json",
        "",
        "///|",
        "fn builtin_entries() -> Array[(String, MappingEntry)] {",
        "  [",
    ]
    lines += [f"    ({json.dumps(key)}, {value})," for key, value in entries]
    lines += ["  ]", "}", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {len(entries)} entries to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
