import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const server = spawn(process.execPath, [fileURLToPath(new URL('./serve.js', import.meta.url))], {
  env: { ...process.env, MORPHIR_WORKBENCH_PORT: '0' }, stdio: ['ignore', 'pipe', 'inherit'],
});
let browser;
try {
  const [output] = await once(server.stdout, 'data');
  const url = String(output).match(/http:\/\/127\.0\.0\.1:\d+/)[0];
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.getByRole('status').filter({ hasText: 'ready to compile' }).waitFor();
  await page.locator('#source .cm-editor').waitFor();
  assert.equal(await page.locator('#source .cm-lineNumbers').count(), 1);
  assert.equal(await page.locator('#source .cm-content').getAttribute('spellcheck'), 'false');
  const syntaxColors = await page.locator('#source .cm-line span').evaluateAll(tokens => [...new Set(tokens.map(token => getComputedStyle(token).color))]);
  assert.ok(syntaxColors.includes('rgb(123, 63, 176)'), 'Scheme numbers are highlighted');
  assert.ok(syntaxColors.includes('rgb(0, 114, 158)'), 'Scheme builtins are highlighted');
  assert.ok(await page.locator('#source .cm-line span').evaluateAll(tokens => tokens.some(token => getComputedStyle(token).fontStyle === 'italic')), 'Scheme comments are highlighted');
  await page.getByRole('button', { name: 'Compile & run', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  assert.equal(await page.locator('.run-value strong').textContent(), '41');
  assert.match(await page.locator('#output').evaluate(editor => editor.value), /formatVersion/);
  assert.equal(await page.getByRole('textbox', { name: 'Morphir IR', exact: true }).getAttribute('aria-readonly'), 'true');
  assert.ok(await page.locator('#output .cm-line span').count() > 0, 'JSON output is highlighted');
  const compiledIr = JSON.parse(await page.locator('#output').evaluate(editor => editor.value));

  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('.tree-item').filter({ hasText: 'total' }).click();
  assert.match(await page.locator('.type-signature').textContent(), /total/);
  await page.getByRole('button', { name: 'IR JSON', exact: true }).click();
  assert.match(await page.locator('#model-detail').evaluate(editor => editor.value), /Apply/);
  await page.getByRole('button', { name: 'Details', exact: true }).click();
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.locator('#context-navigation').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  await page.locator('#context-navigation').waitFor({ state: 'visible' });
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('#context-navigation').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.type-signature').textContent(), /total/);
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();

  await page.getByRole('textbox', { name: 'Source editor' }).fill('(+ 20 22)');
  await page.getByText('Source changed · rerun').waitFor();
  await page.getByRole('textbox', { name: 'Source editor' }).press('End');
  await page.keyboard.insertText(' ');
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  await page.getByRole('textbox', { name: 'Source editor' }).press('ControlOrMeta+z');
  // CodeMirror may group nearby edits; verify undo/redo without depending on timing.
  await page.waitForFunction(() => document.querySelector('#source').value !== '(+ 20 22) ');
  await page.getByRole('textbox', { name: 'Source editor' }).press('ControlOrMeta+Shift+z');
  await page.waitForFunction(() => document.querySelector('#source').value === '(+ 20 22) ');
  await page.getByRole('button', { name: 'Compile & run', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.waitForFunction(() => document.querySelector('.run-value strong')?.textContent === '42');
  await page.getByRole('button', { name: 'Generated', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#output')?.value.includes('morphir'));
  await page.getByRole('button', { name: 'Worksheet', exact: true }).click();
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Worksheet finished' }).waitFor();
  const values = await page.locator('.worksheet-result .value').allTextContents();
  assert.ok(values.includes('49')); assert.ok(values.includes('(1 4 9 16)')); assert.ok(values.includes('1'));
  await page.getByRole('button', { name: 'Compile & inspect', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.run-value strong')?.textContent === '42');
  await page.getByRole('button', { name: 'Worksheet', exact: true }).click();
  await page.waitForFunction(() => [...document.querySelectorAll('.worksheet-result .value')].some(node => node.textContent === '49'));

  await page.getByRole('textbox', { name: 'Source editor' }).fill('(let ((x 1))');
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.waitForFunction(() => /[Uu]nterminated|[Uu]nexpected|[Ll]ist|[Ee]nd/.test(document.querySelector('.statusbar').textContent));
  assert.match(await page.getByRole('status').textContent(), /[Uu]nterminated|[Uu]nexpected|[Ll]ist|[Ee]nd/);
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(let loop ((x 0)) (loop (+ x 1)))');
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Cancelled' }).waitFor();
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(+ 2 2)');
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Worksheet finished' }).waitFor();
  assert.deepEqual(await page.locator('.worksheet-result .value').allTextContents(), ['4']);

  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  const chooserPromise = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Import model', exact: true }).first().click();
  await (await chooserPromise).setFiles(fileURLToPath(new URL('../../../pkgs/morphir-ir/conformance/fixtures/v3-greeting.json', import.meta.url)));
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.getByRole('button', { name: 'IR JSON', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#model-detail')?.value.includes('elm-compat'));
  assert.match(await page.locator('#model-detail').evaluate(editor => editor.value), /elm-compat/);
  await page.getByRole('button', { name: 'Details', exact: true }).click();
  await page.locator('.model-metrics strong').first().waitFor();
  assert.deepEqual(await page.locator('.model-metrics strong').allTextContents(), ['2', '8', '7']);
  if (!await page.locator('#context-navigation').isVisible()) await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.getByRole('button', { name: 'Collapse main', exact: true }).click();
  await page.getByRole('button', { name: 'T Product', exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('Product');
  await page.getByRole('button', { name: 'T Product', exact: true }).click();
  await page.getByRole('heading', { name: 'Product', exact: true }).waitFor();
  assert.match(await page.locator('.declaration-doc').textContent(), /product with price information/);
  assert.deepEqual(await page.locator('.inspector-table tbody td:first-child').allTextContents(), ['id', 'name', 'price']);
  await page.locator('.reference-link').filter({ hasText: 'Main.ProductId' }).click();
  await page.getByRole('heading', { name: 'ProductId', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Used by', exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('');
  await page.getByRole('button', { name: 'T Product', exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Expand main', exact: true }).click();
  await page.locator('.model-tree .tree-item[title="elm-compat:main#apply-discount"]').click();
  await page.getByRole('heading', { name: 'applyDiscount', exact: true }).waitFor();
  assert.match(await page.locator('.type-signature').textContent(), /applyDiscount.*Basics.Float/);
  assert.deepEqual(await page.locator('.inspector-table tbody td:first-child').allTextContents(), ['discountPercent', 'originalPrice']);
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).fill('20');
  await page.getByRole('textbox', { name: 'originalPrice', exact: true }).fill('100');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).fill('1e');
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).press('End');
  await page.keyboard.insertText('+1');
  assert.equal(await page.getByRole('textbox', { name: 'discountPercent', exact: true }).inputValue(), '1e+1');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  const argumentsEditor = page.getByRole('textbox', { name: 'Function arguments', exact: true });
  await argumentsEditor.fill('[20, 100]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await argumentsEditor.fill('[10, 100]');
  await page.getByText('Inputs changed · evaluate again', { exact: true }).waitFor();
  await argumentsEditor.fill('["bad", 100]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Evaluation failed' }).waitFor();
  assert.match(await page.locator('.evaluation-result pre').textContent(), /finite float/);
  await argumentsEditor.fill('[20]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Evaluation failed' }).waitFor();
  await page.locator('.evaluation-result pre').filter({ hasText: 'Expected 2 arguments' }).waitFor();
  // A lone opening bracket can be completed by CodeMirror into valid JSON.
  await argumentsEditor.fill('not valid json');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.locator('.evaluation-result pre').filter({ hasText: 'valid JSON array' }).waitFor();
  // Hold a real worker reply at the host boundary to exercise late-result guards.
  await page.evaluate(() => {
    const request = globalThis.morphirWorkbench.request.bind(globalThis.morphirWorkbench);
    globalThis.morphirWorkbench.request = (data, receive) => request(data, reply => {
      if (data.operation === 'evaluate') globalThis.releaseEvaluation = () => { delete globalThis.releaseEvaluation; receive(reply); };
      else receive(reply);
    });
    globalThis.restoreRequests = () => { globalThis.morphirWorkbench.request = request; };
  });
  await argumentsEditor.fill('[20, 100]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseEvaluation === 'function');
  await argumentsEditor.fill('[10, 100]');
  await page.evaluate(() => globalThis.releaseEvaluation());
  await page.getByRole('status').filter({ hasText: 'Finished for earlier inputs' }).waitFor();
  assert.equal(await page.locator('.evaluation-result.stale pre').textContent(), '80.0');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseEvaluation === 'function');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Cancelled' }).waitFor();
  await page.evaluate(() => globalThis.releaseEvaluation());
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseEvaluation === 'function');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#order-status-to-string"]').click();
  await page.getByRole('heading', { name: 'orderStatusToString', exact: true }).waitFor();
  await page.evaluate(() => globalThis.releaseEvaluation());
  await page.getByRole('status').filter({ hasText: 'Finished for another function' }).waitFor();
  assert.equal(await page.locator('.evaluation-result').count(), 0);
  await page.evaluate(() => globalThis.restoreRequests());
  await argumentsEditor.fill('[{"constructor":"elm-compat:main#shipped","arguments":[]}]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '"Shipped"');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#is-valid-order"]').click();
  await page.getByRole('heading', { name: 'isValidOrder', exact: true }).waitFor();
  const order = { 'order-id': 'order-1', products: [[{ id: 'sku-1', name: 'Book', price: 12.5 }, '2']], status: { constructor: 'elm-compat:main#confirmed', arguments: [] } };
  await argumentsEditor.fill(JSON.stringify([order]));
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '#t');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#calculate-total"]').click();
  await page.getByRole('heading', { name: 'calculateTotal', exact: true }).waitFor();
  await argumentsEditor.fill(JSON.stringify([order]));
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '25.0');
  // Switch the same record document to fields and modify a nested product tuple.
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  const price = page.getByRole('textbox', { name: 'order.products[1][1].price', exact: true });
  await price.fill('15.00');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.locator('.evaluation-result pre').filter({ hasText: '30.0' }).waitFor();
  await page.getByRole('button', { name: 'Add item to order.products', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.products[2][1].price', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Remove order.products[1]', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.products[2][1].price', exact: true }).waitFor({ state: 'hidden' });
  assert.equal(await price.inputValue(), '0');
  await page.getByRole('button', { name: 'Remove order.products[1]', exact: true }).click();
  await page.getByRole('button', { name: 'Add item to order.products', exact: true }).click();
  await price.fill('2.50');
  await page.getByRole('textbox', { name: 'order.products[1][2]', exact: true }).fill('9007199254740993');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#evaluation-input')?.value.includes('9007199254740993'));
  assert.match(await page.locator('#evaluation-input').evaluate(editor => editor.value), /2\.50/);
  await argumentsEditor.fill('[true]');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.locator('.argument-shape-error').waitFor();
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  assert.equal(await page.locator('#evaluation-input').evaluate(editor => editor.value), '[true]');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('button', { name: 'Reset inputs', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.order-id', exact: true }).fill('first line\nsecond line');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await page.waitForFunction(() => { const editor = document.querySelector('#evaluation-input'); return editor && JSON.parse(editor.value)[0]['order-id'] === 'first line\nsecond line'; });
  // A lone opening bracket can be completed by CodeMirror into valid JSON.
  await argumentsEditor.fill('not valid json');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('button', { name: 'Reset inputs', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.order-id', exact: true }).waitFor();
  // Inspect a real nested return value, not a parsed Scheme string or mock reply.
  await page.locator('.model-tree .tree-item[title="elm-compat:api#create-order"]').click();
  await page.getByRole('textbox', { name: 'orderId', exact: true }).fill('<script>\norder-1');
  await page.getByRole('button', { name: 'Add item to products', exact: true }).click();
  await page.getByRole('textbox', { name: 'products[1][1].id', exact: true }).fill('sku-1');
  await page.getByRole('textbox', { name: 'products[1][1].name', exact: true }).fill('Book');
  await page.getByRole('textbox', { name: 'products[1][1].price', exact: true }).fill('12.5');
  await page.getByRole('textbox', { name: 'products[1][2]', exact: true }).fill('9007199254740993');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  const resultRoot = page.locator('.result-view > .result-branch');
  await resultRoot.waitFor();
  assert.deepEqual(await resultRoot.locator(':scope > .result-children > * > .result-node-title > strong, :scope > .result-children > details > summary strong').allTextContents(), ['order-id', 'products', 'status']);
  assert.equal(await page.locator('.result-view script').count(), 0);
  await resultRoot.locator(':scope > summary').focus();
  await page.keyboard.press('Enter');
  assert.equal(await resultRoot.getAttribute('open'), null, 'Result branches collapse with the keyboard');
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: 'Result JSON', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  const resultJson = JSON.parse(await page.locator('#evaluation-output').evaluate(editor => editor.value));
  assert.equal(resultJson.kind, 'record');
  assert.equal(resultJson.fields[0].value.text, JSON.stringify('<script>\norder-1'));
  const tuple = resultJson.fields[1].value.items[0];
  assert.equal(tuple.kind, 'tuple');
  assert.equal(tuple.items[1].text, '9007199254740993');
  const priceResult = tuple.items[0].fields.find(field => field.name === 'price').value;
  const floatBits = new DataView(new ArrayBuffer(8)); floatBits.setFloat64(0, 12.5);
  assert.equal(priceResult.bits, floatBits.getBigUint64(0).toString());
  assert.equal(resultJson.fields[2].value.tag, 'elm-compat:main#pending');
  assert.equal(await page.locator('#evaluation-output .cm-content').getAttribute('contenteditable'), 'false');
  await page.getByRole('textbox', { name: 'orderId', exact: true }).fill('changed');
  await page.getByText('Inputs changed · evaluate again', { exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(editor => editor.value)), resultJson, 'View changes retain the previous result');
  await page.getByRole('button', { name: 'Printed', exact: true }).click();
  await page.getByRole('textbox', { name: 'Printed result', exact: true }).waitFor();
  assert.match(await page.locator('#evaluation-output').evaluate(editor => editor.value), /9007199254740993/);
  await page.getByRole('button', { name: 'Value', exact: true }).click();
  await page.locator('.result-branch summary').filter({ hasText: 'Tuple / vector' }).click();
  await page.locator('.result-view pre').filter({ hasText: '9007199254740993' }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Nested result fits mobile');
  const resultBounds = await page.locator('.result-view').boundingBox();
  for (const button of await page.getByRole('group', { name: 'Result view' }).getByRole('button').all()) {
    const bounds = await button.boundingBox();
    assert.ok(bounds.x + bounds.width <= resultBounds.x + resultBounds.width + 1, 'Result controls remain inside their mobile panel');
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('.model-tree .tree-item[title="elm-compat:main#order-status-to-string"]').click();
  await page.getByRole('combobox', { name: 'status constructor', exact: true }).selectOption({ label: 'Shipped' });
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '"Shipped"');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#order-status-to-string"]').click();
  await page.locator('.reference-link').filter({ hasText: 'Main.Pending' }).click();
  await page.getByRole('heading', { name: 'OrderStatus', exact: true }).waitFor();
  assert.ok((await page.locator('.constructor-list strong').allTextContents()).includes('Pending'));
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('does-not-exist');
  await page.getByText('No declarations match this search.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Find a declaration' }).inputValue(), 'does-not-exist');
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export IR', exact: true }).click();
  assert.equal((await downloadPromise).suggestedFilename(), 'morphir-ir.json');

  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);

  await page.goto(`${url}/?mode=connected`);
  await page.getByRole('status').filter({ hasText: 'launch URL' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Compile', exact: true }).isEnabled(), false);
  const rpcCalls = [];
  await page.route('**/api/session', route => route.fulfill({ json: {
    protocolVersion: 1, webSocketPath: '/rpc', sessionId: 'fixture-session', initialSources: [],
    providers: [{ id: 'fixture', status: 'available', capabilities: ['catalog', 'compile', 'generate'].map(name => ({ name: `morphir/playground/${name}`, version: '1' })) }],
  } }));
  await page.routeWebSocket('**/rpc', socket => {
    socket.onMessage(raw => {
      const request = JSON.parse(raw);
      rpcCalls.push(request);
      const result = request.method.endsWith('catalog') ? {
        frontends: [{ languageId: 'scheme', displayName: 'Fixture Scheme', fileExtensions: ['.scm'], irVersions: ['4.0.0'], compile: true }],
        targets: [{ target: 'scala', displayName: 'Fixture Scala', irVersions: ['4.0.0'], generate: true }],
      } : request.method.endsWith('compile') ? { success: true, ir: compiledIr, irVersion: '4.0.0', diagnostics: [], modules: ['Main'] }
        : request.method.endsWith('generate') ? { success: true, artifacts: [{ path: 'Main.scala', content: 'val answer = 41', binary: false }], diagnostics: [] } : {};
      socket.send(JSON.stringify({ jsonrpc: '2.0', id: request.id, result }));
    });
  });
  await page.goto(`${url}/?mode=connected`);
  await page.getByRole('status').filter({ hasText: 'Connected · ready' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Worksheet', exact: true }).isEnabled(), false);
  assert.equal(await page.getByRole('button', { name: 'Compile & run', exact: true }).isEnabled(), false);
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(total 3)');
  await page.getByRole('combobox', { name: 'Target' }).selectOption('scala');
  await page.getByRole('button', { name: 'Compile', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.getByRole('button', { name: 'Generated', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#output')?.value.includes('val answer = 41'));
  assert.deepEqual(rpcCalls.map(call => call.method), ['morphir.session.initialize', 'morphir.playground.catalog', 'morphir.playground.compile', 'morphir.playground.generate']);
  assert.deepEqual(rpcCalls[2].params.package, { name: 'user' });
  assert.equal(rpcCalls[2].params.documents[0].text, '(total 3)');
  const generated = page.getByRole('textbox', { name: 'Generated output', exact: true });
  assert.equal(await generated.getAttribute('aria-readonly'), 'true');
  assert.ok(await page.locator('#output .cm-line span').count() > 0, 'Host Scala output is highlighted');
  assert.equal(rpcCalls[2].params.irVersion, '4.0.0');
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('.tree-item[title="user:main#main"]').click();
  await page.getByText('Evaluation is unavailable in connected protocol v1.', { exact: false }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Evaluate', exact: true }).count(), 0);
  assert.equal(rpcCalls.length, 4);
  // The tagged mode uses the merged execution codec, including values that
  // cannot pass through ordinary JavaScript numbers or Unicode scalar strings.
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(url);
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  const typedChooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Import model', exact: true }).first().click();
  await (await typedChooser).setFiles(fileURLToPath(new URL('../fixtures/typed-pricing.json', import.meta.url)));
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.locator('.tree-item[title="pricing:quotes#total"]').click();
  await page.getByRole('button', { name: 'Typed invocation', exact: true }).click();
  await page.getByRole('textbox', { name: 'quote.price.coefficient', exact: true }).fill('125');
  await page.getByRole('textbox', { name: 'quote.price.exponent', exact: true }).fill('-1');
  await page.getByRole('textbox', { name: 'quote.quantity', exact: true }).fill('3');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByText('Result · scheme-portable-v1/shared-sdk/bounded', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  const typedArguments = page.getByRole('textbox', { name: 'Function arguments', exact: true });
  await typedArguments.fill(JSON.stringify([{ type: 'record', fields: [
    { name: 'price', value: { type: 'decimal', coefficient: '125', exponent: -1 } },
    { name: 'quantity', value: { type: 'int', value: '3' } },
  ] }]));
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  await page.getByText('Result · scheme-portable-v1/shared-sdk/bounded', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Result JSON', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), { type: 'decimal', coefficient: '375', exponent: -1 });
  await typedArguments.fill('[{"type":"int","value":"3"}]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.locator('.evaluation-result pre').filter({ hasText: 'execution.wrong_type' }).waitFor();
  await page.locator('.tree-item[title="pricing:boundaries#text"]').click();
  await typedArguments.fill('[{"type":"text","units":[55296,0,55357,56832]}]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), { type: 'text', units: [55296,0,55357,56832] });
  await page.locator('.tree-item[title="pricing:results#failure"]').click();
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByText('Result · scheme-portable-v1/shared-sdk/bounded · model error', { exact: true }).waitFor();
  await page.locator('.tree-item[title="pricing:scalars#huge"]').click();
  await page.getByRole('button', { name: 'IR JSON', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#model-detail')?.value.includes('1234567890123456789012345678901234567890'));
  await page.getByRole('button', { name: 'Details', exact: true }).click();
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), { type: 'int', value: '1234567890123456789012345678901234567890' });
  const typedDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export IR', exact: true }).click();
  const exportedText = await readFile(await (await typedDownload).path(), 'utf8');
  assert.ok(exportedText.includes('1234567890123456789012345678901234567890'), 'IR export preserves exact integer lexemes');
  await page.locator('.tree-item[title="pricing:quotes#captured"]').click();
  await page.getByText('Typed evaluation requires a public entry', { exact: false }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Evaluate', exact: true }).count(), 0);
  await page.locator('.tree-item[title="pricing:quotes#difference"]').click();
  // Hold a worker callback across a runtime switch; the new request ID rejects it.
  await page.evaluate(() => {
    const request = globalThis.morphirWorkbench.request;
    globalThis.morphirWorkbench.request = (payload, receive) => request(payload, reply => {
      globalThis.releaseTyped = () => receive(reply);
    });
    globalThis.restoreTyped = () => { globalThis.morphirWorkbench.request = request; };
  });
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseTyped === 'function');
  await page.getByRole('button', { name: 'Local Scheme', exact: true }).click();
  await page.evaluate(() => { globalThis.releaseTyped(); globalThis.restoreTyped(); });
  await page.getByRole('status').filter({ hasText: 'Evaluation mode changed' }).waitFor();
  assert.equal(await page.locator('.evaluation-result').count(), 0);
  await page.getByRole('button', { name: 'Typed invocation', exact: true }).click();
  await typedArguments.waitFor();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#evaluation-input').value)[0]?.type === 'int');
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-input').evaluate(e => e.value)), [{type:'int',value:'0'}, {type:'int',value:'0'}]);
  // Every typed field edits the canonical document, including numeric drafts.
  await page.locator('.tree-item[title="pricing:boundaries#decimal"]').click();
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('textbox', { name: 'input.coefficient', exact: true }).fill('9007199254740993');
  await page.getByRole('textbox', { name: 'input.exponent', exact: true }).fill('-');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-input').evaluate(e => e.value)), [{type:'decimal',coefficient:'9007199254740993',exponent:'-'}]);
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'input.exponent', exact: true }).inputValue(), '-');
  await page.getByRole('textbox', { name: 'input.exponent', exact: true }).fill('-2');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'decimal',coefficient:'9007199254740993',exponent:-2});
  await page.locator('.tree-item[title="pricing:boundaries#float"]').click();
  await page.getByRole('textbox', { name: 'input.number', exact: true }).fill('-0.0');
  await page.waitForFunction(() => document.querySelector('input[aria-label="input.bits"]')?.value === '9223372036854775808');
  assert.equal(await page.getByRole('textbox', { name: 'input.bits', exact: true }).inputValue(), '9223372036854775808');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'float64',bits:'9223372036854775808'});
  await page.getByRole('textbox', { name: 'input.bits', exact: true }).fill('9221120237041090561');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  assert.equal(JSON.parse(await page.locator('#evaluation-input').evaluate(e => e.value))[0].bits, '9221120237041090561');
  await page.locator('.tree-item[title="pricing:boundaries#text"]').click();
  await typedArguments.fill('[{"type":"text","units":[55296,0]}]');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'input.text', exact: true }).count(), 0);
  await page.getByRole('textbox', { name: 'input.units[1]', exact: true }).fill('65');
  await page.getByRole('textbox', { name: 'input.text', exact: true }).fill('A😀\nB');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-input').evaluate(e => e.value))[0].units, [65,55357,56832,10,66]);
  await page.locator('.tree-item[title="pricing:quotes#status-amount"]').click();
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('combobox', { name: 'status constructor', exact: true }).selectOption('pricing:quotes#approved');
  await page.getByRole('textbox', { name: 'status.1.coefficient', exact: true }).fill('375');
  await page.getByRole('textbox', { name: 'status.1.exponent', exact: true }).fill('-1');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'decimal',coefficient:'375',exponent:-1});
  await page.locator('.tree-item[title="pricing:boundaries#maybe"]').click();
  await page.getByRole('combobox', { name: 'input case', exact: true }).selectOption('just');
  await page.getByRole('textbox', { name: 'input.1', exact: true }).fill('9007199254740993');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'maybe',case:'just',value:{type:'int',value:'9007199254740993'}});
  await page.locator('.tree-item[title="pricing:boundaries#result"]').click();
  await page.getByRole('combobox', { name: 'input case', exact: true }).selectOption('err');
  await page.getByRole('textbox', { name: 'input.1.text', exact: true }).fill('Error');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'result',case:'err',value:{type:'text',units:[69,114,114,111,114]}});
  await page.locator('.tree-item[title="pricing:boundaries#tuple"]').click();
  await page.getByRole('textbox', { name: 'input[1].coefficient', exact: true }).fill('125');
  await page.getByRole('textbox', { name: 'input[1].exponent', exact: true }).fill('-1');
  await page.getByRole('textbox', { name: 'input[2]', exact: true }).fill('9007199254740993');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'tuple',items:[{type:'decimal',coefficient:'125',exponent:-1},{type:'int',value:'9007199254740993'}]});
  await page.locator('.tree-item[title="pricing:boundaries#character"]').click();
  await page.getByRole('textbox', { name: 'input.text', exact: true }).fill('😀');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'character',units:[55357,56832]});
  await page.locator('.tree-item[title="pricing:boundaries#list"]').click();
  await page.getByRole('button', { name: 'Add item to input', exact: true }).click();
  await page.getByRole('textbox', { name: 'input[1]', exact: true }).fill('9007199254740993');
  await page.getByRole('button', { name: 'Add item to input', exact: true }).click();
  await page.getByRole('button', { name: 'Remove input[2]', exact: true }).click();
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'list',items:[{type:'int',value:'9007199254740993'}]});
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await typedArguments.fill('[{"type":"bool","value":true}]');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.locator('.argument-shape-error').waitFor();
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-input').evaluate(e => e.value)), [{type:'bool',value:true}]);
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('button', { name: 'Reset inputs', exact: true }).click();
  await page.getByRole('button', { name: 'Add item to input', exact: true }).waitFor();
  // Ion uses the shared codec and converts back into the same fields/JSON values.
  await page.locator('.tree-item[title="pricing:boundaries#decimal"]').click();
  await page.getByRole('button', { name: 'Ion inputs', exact: true }).click();
  await typedArguments.fill('[12.50] // exact decimal');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'decimal',coefficient:'125',exponent:-1});
  assert.ok(await page.locator('#evaluation-input .cm-line span').evaluateAll(tokens => tokens.some(token => getComputedStyle(token).fontStyle === 'italic')), 'Ion comments are highlighted');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'input.coefficient', exact: true }).inputValue(), '1250');
  assert.equal(await page.getByRole('textbox', { name: 'input.exponent', exact: true }).inputValue(), '-2');
  await page.getByRole('button', { name: 'Ion inputs', exact: true }).click();
  await page.locator('.tree-item[title="pricing:quotes#difference"]').click();
  await typedArguments.fill('[9007199254740993, 1]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'int',value:'9007199254740992'});
  await page.locator('.tree-item[title="pricing:boundaries#text"]').click();
  await typedArguments.fill('[morphir_value::{type:"text",units:[55296,0]}]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'text',units:[55296,0]});
  const ionColors = await page.locator('#evaluation-input .cm-line span').evaluateAll(tokens => [...new Set(tokens.map(token => getComputedStyle(token).color))]);
  assert.ok(ionColors.includes('rgb(123, 63, 176)'), 'Ion numbers are highlighted');
  assert.ok(ionColors.includes('rgb(0, 88, 120)'), 'Ion annotations are highlighted');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'input.text', exact: true }).count(), 0);
  assert.equal(await page.getByRole('textbox', { name: 'input.units[1]', exact: true }).inputValue(), '55296');
  await page.getByRole('button', { name: 'Ion inputs', exact: true }).click();
  await typedArguments.fill('invalid Ion !!!');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Evaluation failed' }).waitFor();
  await page.getByText('Ion: unexpected trailing input', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Cannot switch inputs:' }).waitFor();
  assert.equal(await page.locator('#evaluation-input').evaluate(e => e.value), 'invalid Ion !!!');
  assert.equal(await page.locator('#evaluation-input').getAttribute('data-language'), 'ion');
  await typedArguments.fill('[morphir_value::{type:"text",units:[55296,0]}]');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#evaluation-input').dataset.language === 'json');
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-input').evaluate(e => e.value)), [{type:'text',units:[55296,0]}]);
  await page.getByRole('button', { name: 'Ion inputs', exact: true }).click();
  await page.getByRole('button', { name: 'Local Scheme', exact: true }).click();
  await typedArguments.fill('["local text"]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.equal(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)).text, '"local text"');
  await page.getByRole('button', { name: 'Typed invocation', exact: true }).click();
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.getByText('Input and output types', { exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);

  // Exercise the reusable component's contract independently of app messages.
  const componentPage = await browser.newPage();
  componentPage.on('pageerror', error => errors.push(error.message));
  await componentPage.goto(url);
  await componentPage.locator('#source .cm-editor').waitFor();
  await componentPage.evaluate(() => {
    const editor = document.createElement('morphir-code-editor');
    editor.id = 'component-fixture';
    editor.dataset.document = 'component-contract';
    editor.dataset.language = 'scheme';
    editor.dataset.readonly = 'false';
    editor.setAttribute('aria-label', 'Component fixture');
    editor.value = '(+ 1 2)';
    editor.inputCount = 0;
    editor.addEventListener('input', () => ++editor.inputCount);
    document.body.append(editor);
  });
  const fixture = componentPage.getByRole('textbox', { name: 'Component fixture', exact: true });
  await fixture.press('End');
  await componentPage.keyboard.insertText(' ');
  await componentPage.waitForFunction(() => document.querySelector('#component-fixture').value === '(+ 1 2) ');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => editor.inputCount), 1, 'One change event per user edit');
  await componentPage.evaluate(() => {
    const editor = document.querySelector('#component-fixture');
    editor.value = '(+ 3 4)';
    editor.dataset.language = 'unknown-host-language';
  });
  await componentPage.waitForFunction(() => document.querySelector('#component-fixture').value === '(+ 3 4)');
  assert.ok(await componentPage.locator('#component-fixture .cm-line span').evaluateAll(tokens => tokens.every(token => getComputedStyle(token).color === 'rgb(28, 30, 33)')), 'Unknown languages have no syntax colors');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => editor.inputCount), 1, 'Controlled updates do not echo input');
  await componentPage.evaluate(() => { document.querySelector('#component-fixture').dataset.readonly = 'true'; });
  await componentPage.waitForFunction(() => document.querySelector('#component-fixture').shadowRoot.querySelector('.cm-content').getAttribute('contenteditable') === 'false');
  await fixture.focus();
  await componentPage.keyboard.type('cannot edit');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => editor.value), '(+ 3 4)', 'Read-only documents reject editing');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => { editor.remove(); return editor.view; }), null, 'Unmount destroys CodeMirror');
  await componentPage.close();
  assert.deepEqual(errors, []);
  console.log('Browser workflow passed: local compile/run, explorer, context retention, typed evaluation, Ion conversion/highlighting/invalid drafts and controls (exact Decimal/Int, Float64 bits, UTF-16, Maybe/Result, constructors, records/lists/tuples), structured/JSON/printed results, stale replies, worksheet, cancellation, import/export, mobile, connection failure and connected-v1 compile/generate fixture.');

} finally {
  await browser?.close();
  server.kill();
}
