import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const server = spawn(process.execPath, [fileURLToPath(new URL('./serve.js', import.meta.url))], {
  env: { ...process.env, MORPHIR_WORKBENCH_PORT: '0' }, stdio: ['ignore', 'pipe', 'inherit'],
});
let browser;
try {
  const [output] = await once(server.stdout, 'data');
  const url = String(output).match(/http:\/\/127\.0\.0\.1:\d+/)[0];
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.getByRole('status').filter({ hasText: 'ready to compile' }).waitFor();
  await page.locator('#source .cm-editor').waitFor();
  assert.equal(await page.locator('#source .cm-lineNumbers').count(), 1);
  assert.equal(await page.locator('#source .cm-content').getAttribute('spellcheck'), 'false');
  const syntaxColors = await page.locator('#source .cm-line span').evaluateAll(tokens => [...new Set(tokens.map(token => getComputedStyle(token).color))]);
  assert.ok(syntaxColors.includes('rgb(123, 63, 176)'), 'Scheme numbers are highlighted');
  assert.ok(syntaxColors.includes('rgb(0, 114, 158)'), 'Scheme builtins are highlighted');
  assert.ok(await page.locator('#source .cm-line span').evaluateAll(tokens => tokens.some(token => getComputedStyle(token).fontStyle === 'italic')), 'Scheme comments are highlighted');
  await page.getByRole('button', { name: 'Compile & run', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  assert.equal(await page.locator('.run-value strong').textContent(), '41');
  assert.match(await page.locator('#output').evaluate(editor => editor.value), /formatVersion/);
  assert.equal(await page.getByRole('textbox', { name: 'Morphir IR', exact: true }).getAttribute('aria-readonly'), 'true');
  assert.ok(await page.locator('#output .cm-line span').count() > 0, 'JSON output is highlighted');
  const compiledIr = JSON.parse(await page.locator('#output').evaluate(editor => editor.value));

  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('.tree-item').filter({ hasText: 'total' }).click();
  assert.match(await page.locator('.type-signature').textContent(), /total/);
  await page.getByRole('button', { name: 'IR JSON', exact: true }).click();
  assert.match(await page.locator('#model-detail').evaluate(editor => editor.value), /Apply/);
  await page.getByRole('button', { name: 'Details', exact: true }).click();
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.locator('#context-navigation').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  await page.locator('#context-navigation').waitFor({ state: 'visible' });
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('#context-navigation').waitFor({ state: 'hidden' });
  assert.match(await page.locator('.type-signature').textContent(), /total/);
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();

  await page.getByRole('textbox', { name: 'Source editor' }).fill('(+ 20 22)');
  await page.getByText('Source changed · rerun').waitFor();
  await page.getByRole('textbox', { name: 'Source editor' }).press('End');
  await page.keyboard.insertText(' ');
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  await page.getByRole('textbox', { name: 'Source editor' }).press('ControlOrMeta+z');
  // CodeMirror may group nearby edits; verify undo/redo without depending on timing.
  await page.waitForFunction(() => document.querySelector('#source').value !== '(+ 20 22) ');
  await page.getByRole('textbox', { name: 'Source editor' }).press('ControlOrMeta+Shift+z');
  await page.waitForFunction(() => document.querySelector('#source').value === '(+ 20 22) ');
  await page.getByRole('button', { name: 'Compile & run', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.waitForFunction(() => document.querySelector('.run-value strong')?.textContent === '42');
  await page.getByRole('button', { name: 'Generated', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#output')?.value.includes('morphir'));
  await page.getByRole('button', { name: 'Worksheet', exact: true }).click();
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Worksheet finished' }).waitFor();
  const values = await page.locator('.worksheet-result .value').allTextContents();
  assert.ok(values.includes('49')); assert.ok(values.includes('(1 4 9 16)')); assert.ok(values.includes('1'));
  await page.getByRole('button', { name: 'Compile & inspect', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.run-value strong')?.textContent === '42');
  await page.getByRole('button', { name: 'Worksheet', exact: true }).click();
  await page.waitForFunction(() => [...document.querySelectorAll('.worksheet-result .value')].some(node => node.textContent === '49'));

  await page.getByRole('textbox', { name: 'Source editor' }).fill('(let ((x 1))');
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.waitForFunction(() => /[Uu]nterminated|[Uu]nexpected|[Ll]ist|[Ee]nd/.test(document.querySelector('.statusbar').textContent));
  assert.match(await page.getByRole('status').textContent(), /[Uu]nterminated|[Uu]nexpected|[Ll]ist|[Ee]nd/);
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(let loop ((x 0)) (loop (+ x 1)))');
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Cancelled' }).waitFor();
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(+ 2 2)');
  await page.getByRole('button', { name: 'Run worksheet', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Worksheet finished' }).waitFor();
  assert.deepEqual(await page.locator('.worksheet-result .value').allTextContents(), ['4']);

  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  const chooserPromise = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Import model', exact: true }).first().click();
  await (await chooserPromise).setFiles(fileURLToPath(new URL('../../../pkgs/morphir-ir/conformance/fixtures/v3-greeting.json', import.meta.url)));
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.getByRole('button', { name: 'IR JSON', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#model-detail')?.value.includes('elm-compat'));
  assert.match(await page.locator('#model-detail').evaluate(editor => editor.value), /elm-compat/);
  await page.getByRole('button', { name: 'Details', exact: true }).click();
  await page.locator('.model-metrics strong').first().waitFor();
  assert.deepEqual(await page.locator('.model-metrics strong').allTextContents(), ['2', '8', '7']);
  if (!await page.locator('#context-navigation').isVisible()) await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.getByRole('button', { name: 'Collapse main', exact: true }).click();
  await page.getByRole('button', { name: 'T Product', exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('Product');
  await page.getByRole('button', { name: 'T Product', exact: true }).click();
  await page.getByRole('heading', { name: 'Product', exact: true }).waitFor();
  assert.match(await page.locator('.declaration-doc').textContent(), /product with price information/);
  assert.deepEqual(await page.locator('.inspector-table tbody td:first-child').allTextContents(), ['id', 'name', 'price']);
  await page.locator('.reference-link').filter({ hasText: 'Main.ProductId' }).click();
  await page.getByRole('heading', { name: 'ProductId', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Used by', exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('');
  await page.getByRole('button', { name: 'T Product', exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Expand main', exact: true }).click();
  await page.locator('.model-tree .tree-item[title="elm-compat:main#apply-discount"]').click();
  await page.getByRole('heading', { name: 'applyDiscount', exact: true }).waitFor();
  assert.match(await page.locator('.type-signature').textContent(), /applyDiscount.*Basics.Float/);
  assert.deepEqual(await page.locator('.inspector-table tbody td:first-child').allTextContents(), ['discountPercent', 'originalPrice']);
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).fill('20');
  await page.getByRole('textbox', { name: 'originalPrice', exact: true }).fill('100');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).fill('1e');
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).press('End');
  await page.keyboard.insertText('+1');
  assert.equal(await page.getByRole('textbox', { name: 'discountPercent', exact: true }).inputValue(), '1e+1');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  const argumentsEditor = page.getByRole('textbox', { name: 'Function arguments', exact: true });
  await argumentsEditor.fill('[20, 100]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await argumentsEditor.fill('[10, 100]');
  await page.getByText('Inputs changed · evaluate again', { exact: true }).waitFor();
  await argumentsEditor.fill('["bad", 100]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Evaluation failed' }).waitFor();
  assert.match(await page.locator('.evaluation-result pre').textContent(), /finite float/);
  await argumentsEditor.fill('[20]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Evaluation failed' }).waitFor();
  await page.locator('.evaluation-result pre').filter({ hasText: 'Expected 2 arguments' }).waitFor();
  // A lone opening bracket can be completed by CodeMirror into valid JSON.
  await argumentsEditor.fill('not valid json');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.locator('.evaluation-result pre').filter({ hasText: 'valid JSON array' }).waitFor();
  // Hold a real worker reply at the host boundary to exercise late-result guards.
  await page.evaluate(() => {
    const request = globalThis.morphirWorkbench.request.bind(globalThis.morphirWorkbench);
    globalThis.morphirWorkbench.request = (data, receive) => request(data, reply => {
      if (data.operation === 'evaluate') globalThis.releaseEvaluation = () => { delete globalThis.releaseEvaluation; receive(reply); };
      else receive(reply);
    });
    globalThis.restoreRequests = () => { globalThis.morphirWorkbench.request = request; };
  });
  await argumentsEditor.fill('[20, 100]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseEvaluation === 'function');
  await argumentsEditor.fill('[10, 100]');
  await page.evaluate(() => globalThis.releaseEvaluation());
  await page.getByRole('status').filter({ hasText: 'Finished for earlier inputs' }).waitFor();
  assert.equal(await page.locator('.evaluation-result.stale pre').textContent(), '80.0');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseEvaluation === 'function');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Cancelled' }).waitFor();
  await page.evaluate(() => globalThis.releaseEvaluation());
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.waitForFunction(() => typeof globalThis.releaseEvaluation === 'function');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#order-status-to-string"]').click();
  await page.getByRole('heading', { name: 'orderStatusToString', exact: true }).waitFor();
  await page.evaluate(() => globalThis.releaseEvaluation());
  await page.getByRole('status').filter({ hasText: 'Finished for another function' }).waitFor();
  assert.equal(await page.locator('.evaluation-result').count(), 0);
  await page.evaluate(() => globalThis.restoreRequests());
  await argumentsEditor.fill('[{"constructor":"elm-compat:main#shipped","arguments":[]}]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '"Shipped"');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#is-valid-order"]').click();
  await page.getByRole('heading', { name: 'isValidOrder', exact: true }).waitFor();
  const order = { 'order-id': 'order-1', products: [[{ id: 'sku-1', name: 'Book', price: 12.5 }, '2']], status: { constructor: 'elm-compat:main#confirmed', arguments: [] } };
  await argumentsEditor.fill(JSON.stringify([order]));
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '#t');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#calculate-total"]').click();
  await page.getByRole('heading', { name: 'calculateTotal', exact: true }).waitFor();
  await argumentsEditor.fill(JSON.stringify([order]));
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '25.0');
  // Switch the same record document to fields and modify a nested product tuple.
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  const price = page.getByRole('textbox', { name: 'order.products[1][1].price', exact: true });
  await price.fill('15.00');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.locator('.evaluation-result pre').filter({ hasText: '30.0' }).waitFor();
  await page.getByRole('button', { name: 'Add item to order.products', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.products[2][1].price', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Remove order.products[1]', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.products[2][1].price', exact: true }).waitFor({ state: 'hidden' });
  assert.equal(await price.inputValue(), '0');
  await page.getByRole('button', { name: 'Remove order.products[1]', exact: true }).click();
  await page.getByRole('button', { name: 'Add item to order.products', exact: true }).click();
  await price.fill('2.50');
  await page.getByRole('textbox', { name: 'order.products[1][2]', exact: true }).fill('9007199254740993');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#evaluation-input')?.value.includes('9007199254740993'));
  assert.match(await page.locator('#evaluation-input').evaluate(editor => editor.value), /2\.50/);
  await argumentsEditor.fill('[true]');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.locator('.argument-shape-error').waitFor();
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  assert.equal(await page.locator('#evaluation-input').evaluate(editor => editor.value), '[true]');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('button', { name: 'Reset inputs', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.order-id', exact: true }).fill('first line\nsecond line');
  await page.getByRole('button', { name: 'JSON inputs', exact: true }).click();
  await page.waitForFunction(() => { const editor = document.querySelector('#evaluation-input'); return editor && JSON.parse(editor.value)[0]['order-id'] === 'first line\nsecond line'; });
  // A lone opening bracket can be completed by CodeMirror into valid JSON.
  await argumentsEditor.fill('not valid json');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  await page.getByRole('button', { name: 'Reset inputs', exact: true }).click();
  await page.getByRole('textbox', { name: 'order.order-id', exact: true }).waitFor();
  await page.locator('.model-tree .tree-item[title="elm-compat:main#order-status-to-string"]').click();
  await page.getByRole('combobox', { name: 'status constructor', exact: true }).selectOption({ label: 'Shipped' });
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '"Shipped"');
  await page.locator('.model-tree .tree-item[title="elm-compat:main#order-status-to-string"]').click();
  await page.locator('.reference-link').filter({ hasText: 'Main.Pending' }).click();
  await page.getByRole('heading', { name: 'OrderStatus', exact: true }).waitFor();
  assert.ok((await page.locator('.constructor-list strong').allTextContents()).includes('Pending'));
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('does-not-exist');
  await page.getByText('No declarations match this search.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Find a declaration' }).inputValue(), 'does-not-exist');
  await page.getByRole('textbox', { name: 'Find a declaration' }).fill('');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export IR', exact: true }).click();
  assert.equal((await downloadPromise).suggestedFilename(), 'morphir-ir.json');

  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Try Morphir', exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);

  await page.goto(`${url}/?mode=connected`);
  await page.getByRole('status').filter({ hasText: 'launch URL' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Compile', exact: true }).isEnabled(), false);
  const rpcCalls = [];
  await page.route('**/api/session', route => route.fulfill({ json: {
    protocolVersion: 1, webSocketPath: '/rpc', sessionId: 'fixture-session', initialSources: [],
    providers: [{ id: 'fixture', status: 'available', capabilities: ['catalog', 'compile', 'generate'].map(name => ({ name: `morphir/playground/${name}`, version: '1' })) }],
  } }));
  await page.routeWebSocket('**/rpc', socket => {
    socket.onMessage(raw => {
      const request = JSON.parse(raw);
      rpcCalls.push(request);
      const result = request.method.endsWith('catalog') ? {
        frontends: [{ languageId: 'scheme', displayName: 'Fixture Scheme', fileExtensions: ['.scm'], irVersions: ['4.0.0'], compile: true }],
        targets: [{ target: 'scala', displayName: 'Fixture Scala', irVersions: ['4.0.0'], generate: true }],
      } : request.method.endsWith('compile') ? { success: true, ir: compiledIr, irVersion: '4.0.0', diagnostics: [], modules: ['Main'] }
        : request.method.endsWith('generate') ? { success: true, artifacts: [{ path: 'Main.scala', content: 'val answer = 41', binary: false }], diagnostics: [] } : {};
      socket.send(JSON.stringify({ jsonrpc: '2.0', id: request.id, result }));
    });
  });
  await page.goto(`${url}/?mode=connected`);
  await page.getByRole('status').filter({ hasText: 'Connected · ready' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Worksheet', exact: true }).isEnabled(), false);
  assert.equal(await page.getByRole('button', { name: 'Compile & run', exact: true }).isEnabled(), false);
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(total 3)');
  await page.getByRole('combobox', { name: 'Target' }).selectOption('scala');
  await page.getByRole('button', { name: 'Compile', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.getByRole('button', { name: 'Generated', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#output')?.value.includes('val answer = 41'));
  assert.deepEqual(rpcCalls.map(call => call.method), ['morphir.session.initialize', 'morphir.playground.catalog', 'morphir.playground.compile', 'morphir.playground.generate']);
  assert.deepEqual(rpcCalls[2].params.package, { name: 'user' });
  assert.equal(rpcCalls[2].params.documents[0].text, '(total 3)');
  const generated = page.getByRole('textbox', { name: 'Generated output', exact: true });
  assert.equal(await generated.getAttribute('aria-readonly'), 'true');
  assert.ok(await page.locator('#output .cm-line span').count() > 0, 'Host Scala output is highlighted');
  assert.equal(rpcCalls[2].params.irVersion, '4.0.0');
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('.tree-item[title="user:main#main"]').click();
  await page.getByText('Evaluation is unavailable in connected protocol v1.', { exact: false }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Evaluate', exact: true }).count(), 0);
  assert.equal(rpcCalls.length, 4);
  // Exercise the reusable component's contract independently of app messages.
  const componentPage = await browser.newPage();
  componentPage.on('pageerror', error => errors.push(error.message));
  await componentPage.goto(url);
  await componentPage.locator('#source .cm-editor').waitFor();
  await componentPage.evaluate(() => {
    const editor = document.createElement('morphir-code-editor');
    editor.id = 'component-fixture';
    editor.dataset.document = 'component-contract';
    editor.dataset.language = 'scheme';
    editor.dataset.readonly = 'false';
    editor.setAttribute('aria-label', 'Component fixture');
    editor.value = '(+ 1 2)';
    editor.inputCount = 0;
    editor.addEventListener('input', () => ++editor.inputCount);
    document.body.append(editor);
  });
  const fixture = componentPage.getByRole('textbox', { name: 'Component fixture', exact: true });
  await fixture.press('End');
  await componentPage.keyboard.insertText(' ');
  await componentPage.waitForFunction(() => document.querySelector('#component-fixture').value === '(+ 1 2) ');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => editor.inputCount), 1, 'One change event per user edit');
  await componentPage.evaluate(() => {
    const editor = document.querySelector('#component-fixture');
    editor.value = '(+ 3 4)';
    editor.dataset.language = 'unknown-host-language';
  });
  await componentPage.waitForFunction(() => document.querySelector('#component-fixture').value === '(+ 3 4)');
  assert.ok(await componentPage.locator('#component-fixture .cm-line span').evaluateAll(tokens => tokens.every(token => getComputedStyle(token).color === 'rgb(28, 30, 33)')), 'Unknown languages have no syntax colors');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => editor.inputCount), 1, 'Controlled updates do not echo input');
  await componentPage.evaluate(() => { document.querySelector('#component-fixture').dataset.readonly = 'true'; });
  await componentPage.waitForFunction(() => document.querySelector('#component-fixture').shadowRoot.querySelector('.cm-content').getAttribute('contenteditable') === 'false');
  await fixture.focus();
  await componentPage.keyboard.type('cannot edit');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => editor.value), '(+ 3 4)', 'Read-only documents reject editing');
  assert.equal(await componentPage.locator('#component-fixture').evaluate(editor => { editor.remove(); return editor.view; }), null, 'Unmount destroys CodeMirror');
  await componentPage.close();
  assert.deepEqual(errors, []);
  console.log('Browser workflow passed: local compile/run, explorer, context retention, typed evaluation (discount/constructors/records), stale replies, worksheet, cancellation, import/export, mobile, connection failure and connected-v1 compile/generate fixture.');

} finally {
  await browser?.close();
  server.kill();
}
