import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { fileURLToPath } from 'node:url';

if (!process.argv[2]) throw new Error('Usage: node scripts/desktop-test.js http://127.0.0.1:<cdp-port>');
const browser = await chromium.connectOverCDP(process.argv[2]);
try {
  const page = browser.contexts()[0].pages().find(page => page.url().includes('proton.localhost'));
  assert.ok(page, 'Packaged Proton asset page is present');
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('status').filter({ hasText: 'ready to compile' }).waitFor();
  const back = page.getByRole('button', {name:'Back',exact:true});
  assert.equal(await back.isEnabled(), false);
  await page.locator('#source .cm-editor').waitFor();
  assert.ok(await page.locator('#source .cm-line span').count() > 0, 'Packaged source has syntax highlighting');
  await page.getByRole('textbox', { name: 'Source editor' }).fill('(+ 20 22)');
  await page.getByRole('button', { name: 'Compile & run', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.run-value strong')?.textContent === '42');
  await page.getByRole('button', { name: 'Model Explorer', exact: true }).click();
  await page.locator('.tree-item').filter({ hasText: 'main' }).click();
  await page.getByRole('heading', { name: 'Returns', exact: true }).waitFor();
  assert.match(await page.locator('.type-signature').textContent(), /main/);
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '42');
  const chooserPromise = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Import model', exact: true }).first().click();
  await (await chooserPromise).setFiles(fileURLToPath(new URL('../../../pkgs/morphir-ir/conformance/fixtures/v3-greeting.json', import.meta.url)));
  await page.getByRole('button', { name: 'T Product', exact: true }).click();
  await page.getByRole('heading', { name: 'Product', exact: true }).waitFor();
  assert.match(await page.locator('.type-signature').textContent(), /Main.ProductId/);
  await page.locator('.reference-link').filter({ hasText: 'Main.ProductId' }).click();
  await page.getByRole('heading', { name: 'ProductId', exact: true }).waitFor();
  await back.click();
  await page.getByRole('heading', { name: 'Product', exact: true }).waitFor();
  if (process.env.MORPHIR_WORKBENCH_DESKTOP_SCREENSHOT) await page.screenshot({path:process.env.MORPHIR_WORKBENCH_DESKTOP_SCREENSHOT,fullPage:false});
  await page.getByRole('button', {name:'Try Morphir',exact:true}).click();
  await back.click();
  await page.getByRole('heading', { name: 'Product', exact: true }).waitFor();
  await page.locator('.reference-link').filter({hasText:'Main.ProductId'}).click();
  await page.getByRole('heading', { name: 'ProductId', exact: true }).waitFor();
  await page.getByRole('button', { name: 'IR JSON', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#model-detail')?.value.includes('TypeAliasDefinition'));
  await page.getByRole('button', { name: 'Details', exact: true }).click();
  await page.locator('.tree-item[title="elm-compat:main#apply-discount"]').click();
  await page.getByRole('heading', { name: 'applyDiscount', exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'discountPercent', exact: true }).fill('20');
  await page.getByRole('textbox', { name: 'originalPrice', exact: true }).fill('100');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Function evaluated' }).waitFor();
  assert.equal(await page.locator('.evaluation-result pre').textContent(), '80.0');
  await page.locator('.tree-item[title="elm-compat:api#create-order"]').click();
  await page.getByRole('textbox', { name: 'orderId', exact: true }).fill('desktop-order');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.locator('.result-view > .result-branch').waitFor();
  await page.getByRole('button', { name: 'Result JSON', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  const projected = JSON.parse(await page.locator('#evaluation-output').evaluate(editor => editor.value));
  assert.equal(projected.kind, 'record');
  assert.equal(projected.fields.find(field => field.name === 'order-id').value.text, '"desktop-order"');
  assert.equal(projected.fields.find(field => field.name === 'status').value.tag, 'elm-compat:main#pending');
  await page.getByRole('button', { name: 'Printed', exact: true }).click();
  await page.getByRole('textbox', { name: 'Printed result', exact: true }).waitFor();
  assert.match(await page.locator('#evaluation-output').evaluate(editor => editor.value), /desktop-order/);
  await page.getByRole('button', { name: 'Value', exact: true }).click();
  const typedChooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Import model', exact: true }).first().click();
  await (await typedChooser).setFiles(fileURLToPath(new URL('../fixtures/typed-pricing.json', import.meta.url)));
  await page.getByRole('status').filter({ hasText: 'Model ready' }).waitFor();
  await page.locator('.tree-item[title="pricing:quotes#total"]').click();
  await page.getByRole('button', { name: 'Typed invocation', exact: true }).click();
  await page.getByRole('textbox', { name: 'quote.price.coefficient', exact: true }).fill('125');
  await page.getByRole('textbox', { name: 'quote.price.exponent', exact: true }).fill('-1');
  await page.getByRole('textbox', { name: 'quote.quantity', exact: true }).fill('3');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByText('Result · scheme-portable-v1/shared-sdk/bounded', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Result JSON', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), { type: 'decimal', coefficient: '375', exponent: -1 });
  await page.getByRole('button', { name: 'Ion inputs', exact: true }).click();
  const ionEditor = page.getByRole('textbox', { name: 'Function arguments', exact: true });
  await ionEditor.fill('[morphir_value::{type:"record",fields:[{name:"price",value:{type:"decimal",coefficient:"125",exponent:-1}},{name:"quantity",value:{type:"int",value:"3"}}]}]');
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), {type:'decimal',coefficient:'375',exponent:-1});
  assert.ok(await page.locator('#evaluation-input .cm-line span').count() > 0, 'Packaged Ion has syntax highlighting');
  await page.getByRole('button', { name: 'Input fields', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'quote.quantity', exact: true }).inputValue(), '3');
  await page.locator('.tree-item[title="pricing:scalars#huge"]').click();
  await page.getByRole('button', { name: 'Evaluate', exact: true }).click();
  await page.getByRole('textbox', { name: 'Result JSON', exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await page.locator('#evaluation-output').evaluate(e => e.value)), { type: 'int', value: '1234567890123456789012345678901234567890' });
  assert.deepEqual(errors, []);
  console.log('Packaged Proton smoke passed: shared UI, secure assets, worker compile/run, model import/reference/back navigation, typed function evaluation with fields/Ion and structured/JSON/printed result views.');
} finally { await browser.close(); }
