///|
pub extend Literal with Eq::{equal, not_equal}

///|
pub extend Literal with @debug.Debug::{to_repr}

///|
pub extend Pattern with Eq::{equal, not_equal}

///|
pub extend Pattern with @debug.Debug::{to_repr}

///|
pub extend Value with Eq::{equal, not_equal}

///|
pub extend Value with @debug.Debug::{to_repr}

///|
pub extend ValueSpecification with Eq::{equal, not_equal}

///|
pub extend ValueSpecification with @debug.Debug::{to_repr}

///|
pub extend ValueDefinition with Eq::{equal, not_equal}

///|
pub extend ValueDefinition with @debug.Debug::{to_repr}

///|
pub extend Type with Eq::{equal, not_equal}

///|
pub extend Type with @debug.Debug::{to_repr}

///|
pub extend Field with Eq::{equal, not_equal}

///|
pub extend Field with @debug.Debug::{to_repr}

///|
pub extend TypeSpecification with Eq::{equal, not_equal}

///|
pub extend TypeSpecification with @debug.Debug::{to_repr}

///|
pub extend DerivedTypeDetails with Eq::{equal, not_equal}

///|
pub extend DerivedTypeDetails with @debug.Debug::{to_repr}

///|
pub extend TypeDefinition with Eq::{equal, not_equal}

///|
pub extend TypeDefinition with @debug.Debug::{to_repr}

///|
pub extend ModuleSpecification with Eq::{equal, not_equal}

///|
pub extend ModuleSpecification with @debug.Debug::{to_repr}

///|
pub extend ModuleDefinition with Eq::{equal, not_equal}

///|
pub extend ModuleDefinition with @debug.Debug::{to_repr}

///|
pub extend PackageSpecification with Eq::{equal, not_equal}

///|
pub extend PackageSpecification with @debug.Debug::{to_repr}

///|
pub extend PackageDefinition with Eq::{equal, not_equal}

///|
pub extend PackageDefinition with @debug.Debug::{to_repr}

///|
pub extend Distribution with Eq::{equal, not_equal}

///|
pub extend Distribution with @debug.Debug::{to_repr}

///|
pub extend IRFile with Eq::{equal, not_equal}

///|
pub extend IRFile with @debug.Debug::{to_repr}
