(package "morphir/SDK"
  (module basics
    (type int (opaque))
    (type float (opaque))
    (type bool (opaque))
    (type never (opaque))
    (type order (custom (LT) (EQ) (GT)))
    (val add ((a number) (b number)) number)
    (val subtract ((a number) (b number)) number)
    (val multiply ((a number) (b number)) number)
    (val divide ((a basics#float) (b basics#float)) basics#float)
    (val integer-divide ((a basics#int) (b basics#int)) basics#int)
    (val power ((a number) (b number)) number)
    (val to-float ((a basics#int)) basics#float)
    (val round ((a basics#float)) basics#int)
    (val floor ((a basics#float)) basics#int)
    (val ceiling ((a basics#float)) basics#int)
    (val truncate ((a basics#float)) basics#int)
    (val mod-by ((a basics#int) (b basics#int)) basics#int)
    (val remainder-by ((a basics#int) (b basics#int)) basics#int)
    (val negate ((a number)) number)
    (val abs ((a number)) number)
    (val clamp ((a number) (b number) (c number)) number)
    (val is-na-n ((a basics#float)) basics#bool)
    (val is-infinite ((a basics#float)) basics#bool)
    (val sqrt ((a basics#float)) basics#float)
    (val log-base ((a basics#float) (b basics#float)) basics#float)
    (val e () basics#float)
    (val pi () basics#float)
    (val cos ((a basics#float)) basics#float)
    (val sin ((a basics#float)) basics#float)
    (val tan ((a basics#float)) basics#float)
    (val acos ((a basics#float)) basics#float)
    (val asin ((a basics#float)) basics#float)
    (val atan ((a basics#float)) basics#float)
    (val atan-2 ((a basics#float) (b basics#float)) basics#float)
    (val degrees ((a basics#float)) basics#float)
    (val radians ((a basics#float)) basics#float)
    (val turns ((a basics#float)) basics#float)
    (val to-polar ((a (tuple basics#float basics#float))) (tuple basics#float basics#float))
    (val from-polar ((a (tuple basics#float basics#float))) (tuple basics#float basics#float))
    (val equal ((a eq) (b eq)) basics#bool)
    (val not-equal ((a eq) (b eq)) basics#bool)
    (val less-than ((a comparable) (b comparable)) basics#bool)
    (val greater-than ((a comparable) (b comparable)) basics#bool)
    (val less-than-or-equal ((a comparable) (b comparable)) basics#bool)
    (val greater-than-or-equal ((a comparable) (b comparable)) basics#bool)
    (val max ((a comparable) (b comparable)) comparable)
    (val min ((a comparable) (b comparable)) comparable)
    (val compare ((a comparable) (b comparable)) basics#order)
    (val not ((a basics#bool)) basics#bool)
    (val and ((a basics#bool) (b basics#bool)) basics#bool)
    (val or ((a basics#bool) (b basics#bool)) basics#bool)
    (val xor ((a basics#bool) (b basics#bool)) basics#bool)
    (val append ((a appendable) (b appendable)) appendable)
    (val identity ((a a)) a)
    (val always ((a a) (b b)) a)
    (val compose-left ((g (-> b c)) (f (-> a b))) (-> a c))
    (val compose-right ((f (-> a b)) (g (-> b c))) (-> a c))
    (val never ((a basics#never)) a))
  (module string
    (type string (opaque))
    (val is-empty ((s string#string)) basics#bool)
    (val length ((s string#string)) basics#int)
    (val reverse ((s string#string)) string#string)
    (val repeat ((n basics#int) (s string#string)) string#string)
    (val replace ((match string#string) (replacement string#string) (s string#string)) string#string)
    (val append ((s-1 string#string) (s-2 string#string)) string#string)
    (val concat ((list (list#list string#string))) string#string)
    (val split ((sep string#string) (s string#string)) (list#list string#string))
    (val join ((sep string#string) (list (list#list string#string))) string#string)
    (val words ((s string#string)) (list#list string#string))
    (val lines ((s string#string)) (list#list string#string))
    (val slice ((start basics#int) (end basics#int) (s string#string)) string#string)
    (val left ((n basics#int) (s string#string)) string#string)
    (val right ((n basics#int) (s string#string)) string#string)
    (val drop-left ((n basics#int) (s string#string)) string#string)
    (val drop-right ((n basics#int) (s string#string)) string#string)
    (val contains ((ref string#string) (s string#string)) basics#bool)
    (val starts-with ((ref string#string) (s string#string)) basics#bool)
    (val ends-with ((ref string#string) (s string#string)) basics#bool)
    (val indexes ((ref string#string) (s string#string)) (list#list basics#int))
    (val indices ((ref string#string) (s string#string)) (list#list basics#int))
    (val to-int ((s string#string)) (maybe#maybe basics#int))
    (val from-int ((a basics#int)) string#string)
    (val to-float ((s string#string)) (maybe#maybe basics#float))
    (val from-float ((a basics#float)) string#string)
    (val from-char ((ch char#char)) string#string)
    (val cons ((ch char#char) (s string#string)) string#string)
    (val uncons ((s string#string)) (maybe#maybe (tuple char#char string#string)))
    (val to-list ((s string#string)) (list#list char#char))
    (val from-list ((a (list#list char#char))) string#string)
    (val to-upper ((s string#string)) string#string)
    (val to-lower ((s string#string)) string#string)
    (val pad ((n basics#int) (ch char#char) (s string#string)) string#string)
    (val pad-left ((n basics#int) (ch char#char) (s string#string)) string#string)
    (val pad-right ((n basics#int) (ch char#char) (s string#string)) string#string)
    (val trim ((s string#string)) string#string)
    (val trim-left ((s string#string)) string#string)
    (val trim-right ((s string#string)) string#string)
    (val map ((f (-> char#char char#char)) (s string#string)) string#string)
    (val filter ((f (-> char#char basics#bool)) (s string#string)) string#string)
    (val foldl ((f (-> char#char b b)) (z b) (s string#string)) b)
    (val foldr ((f (-> char#char b b)) (z b) (s string#string)) b)
    (val any ((f (-> char#char basics#bool)) (s string#string)) basics#bool)
    (val all ((f (-> char#char basics#bool)) (s string#string)) basics#bool))
  (module list
    (type list (opaque) a)
    (val singleton ((a a)) (list#list a))
    (val repeat ((n basics#int) (a a)) (list#list a))
    (val range ((from basics#int) (to basics#int)) (list#list basics#int))
    (val cons ((head a) (tail (list#list a))) (list#list a))
    (val map ((f (-> a b)) (list (list#list a))) (list#list b))
    (val indexed-map ((f (-> basics#int a b)) (list (list#list a))) (list#list b))
    (val foldl ((f (-> a b b)) (z b) (list (list#list a))) b)
    (val foldr ((f (-> a b b)) (z b) (list (list#list a))) b)
    (val filter ((f (-> a basics#bool)) (list (list#list a))) (list#list a))
    (val filter-map ((f (-> a (maybe#maybe b))) (list (list#list a))) (list#list b))
    (val length ((list (list#list a))) basics#int)
    (val reverse ((list (list#list a))) (list#list a))
    (val member ((ref a) (list (list#list a))) basics#bool)
    (val all ((f (-> a basics#bool)) (list (list#list a))) basics#bool)
    (val any ((f (-> a basics#bool)) (list (list#list a))) basics#bool)
    (val maximum ((list (list#list comparable))) (maybe#maybe comparable))
    (val minimum ((list (list#list comparable))) (maybe#maybe comparable))
    (val sum ((list (list#list number))) number)
    (val product ((list (list#list number))) number)
    (val append ((l-1 (list#list a)) (l-2 (list#list a))) (list#list a))
    (val concat ((lists (list#list (list#list a)))) (list#list a))
    (val concat-map ((f (-> a (list#list b))) (list (list#list a))) (list#list b))
    (val intersperse ((a a) (list (list#list a))) (list#list a))
    (val map-2 ((f (-> a b r)) (list-1 (list#list a)) (list-2 (list#list b))) (list#list r))
    (val map-3 ((f (-> a b c r)) (list-1 (list#list a)) (list-2 (list#list b)) (list-3 (list#list c))) (list#list r))
    (val map-4 ((f (-> a b c d r)) (list-1 (list#list a)) (list-2 (list#list b)) (list-3 (list#list c)) (list-4 (list#list d))) (list#list r))
    (val map-5 ((f (-> a b c d e r)) (list-1 (list#list a)) (list-2 (list#list b)) (list-3 (list#list c)) (list-4 (list#list d)) (list-5 (list#list e))) (list#list r))
    (val sort ((list (list#list comparable))) (list#list comparable))
    (val sort-by ((f (-> a comparable)) (list (list#list a))) (list#list a))
    (val sort-with ((f (-> a a basics#order)) (list (list#list a))) (list#list a))
    (val is-empty ((list (list#list a))) basics#bool)
    (val head ((list (list#list a))) (maybe#maybe a))
    (val tail ((list (list#list a))) (maybe#maybe (list#list a)))
    (val take ((n basics#int) (list (list#list a))) (list#list a))
    (val drop ((n basics#int) (list (list#list a))) (list#list a))
    (val partition ((f (-> a basics#bool)) (list (list#list a))) (tuple (list#list a) (list#list a)))
    (val unzip ((list (list#list (tuple a b)))) (tuple (list#list a) (list#list b)))
    (val inner-join ((list-b (list#list b)) (f (-> a b basics#bool)) (list-a (list#list a))) (list#list (tuple a b)))
    (val left-join ((list-b (list#list b)) (f (-> a b basics#bool)) (list-a (list#list a))) (list#list (tuple a (maybe#maybe b)))))
  (module maybe
    (type maybe (custom (just a) (nothing)) a)
    (val and-then ((f (-> a (maybe#maybe b))) (maybe (maybe#maybe a))) (maybe#maybe b))
    (val map ((f (-> a b)) (maybe (maybe#maybe a))) (maybe#maybe b))
    (val map-2 ((f (-> a b r)) (maybe-1 (maybe#maybe a)) (maybe-2 (maybe#maybe b))) (maybe#maybe r))
    (val map-3 ((f (-> a b c r)) (maybe-1 (maybe#maybe a)) (maybe-2 (maybe#maybe b)) (maybe-3 (maybe#maybe c))) (maybe#maybe r))
    (val map-4 ((f (-> a b c d r)) (maybe-1 (maybe#maybe a)) (maybe-2 (maybe#maybe b)) (maybe-3 (maybe#maybe c)) (maybe-4 (maybe#maybe d))) (maybe#maybe r))
    (val map-5 ((f (-> a b c d e r)) (maybe-1 (maybe#maybe a)) (maybe-2 (maybe#maybe b)) (maybe-3 (maybe#maybe c)) (maybe-4 (maybe#maybe d)) (maybe-5 (maybe#maybe e))) (maybe#maybe r))
    (val with-default ((default a) (maybe (maybe#maybe a))) a)
    (val has-value ((maybe (maybe#maybe a))) basics#bool))
  (module result
    (type result (custom (ok a) (err e)) e a)
    (val and-then ((f (-> a (result#result x b))) (result (result#result x a))) (result#result x b))
    (val map ((f (-> a b)) (result (result#result x a))) (result#result x b))
    (val map-2 ((f (-> a b r)) (result-1 (result#result x a)) (result-2 (result#result x b))) (result#result x r))
    (val map-3 ((f (-> a b c r)) (result-1 (result#result x a)) (result-2 (result#result x b)) (result-3 (result#result x c))) (result#result x r))
    (val map-4 ((f (-> a b c d r)) (result-1 (result#result x a)) (result-2 (result#result x b)) (result-3 (result#result x c)) (result-4 (result#result x d))) (result#result x r))
    (val map-5 ((f (-> a b c d e r)) (result-1 (result#result x a)) (result-2 (result#result x b)) (result-3 (result#result x c)) (result-4 (result#result x d)) (result-5 (result#result x e))) (result#result x r))
    (val with-default ((default a) (result (result#result x a))) a)
    (val to-maybe ((result (result#result x a))) (maybe#maybe a))
    (val from-maybe ((error x) (maybe (maybe#maybe a))) (result#result x a))
    (val map-error ((f (-> x y)) (result (result#result x a))) (result#result y a)))
  (module dict
    (type dict (opaque) k v)
    (val empty () (dict#dict k v))
    (val singleton ((key comparable) (value v)) (dict#dict comparable v))
    (val insert ((key comparable) (value v) (dict (dict#dict comparable v))) (dict#dict comparable v))
    (val update ((key comparable) (f (-> (maybe#maybe v) (maybe#maybe v))) (dict (dict#dict comparable v))) (dict#dict comparable v))
    (val remove ((key comparable) (dict (dict#dict comparable v))) (dict#dict comparable v))
    (val is-empty ((dict (dict#dict comparable v))) basics#bool)
    (val member ((key comparable) (dict (dict#dict comparable v))) basics#bool)
    (val get ((key comparable) (dict (dict#dict comparable v))) (maybe#maybe v))
    (val size ((dict (dict#dict comparable v))) basics#int)
    (val keys ((dict (dict#dict k v))) (list#list k))
    (val values ((dict (dict#dict k v))) (list#list v))
    (val to-list ((dict (dict#dict k v))) (list#list (tuple k v)))
    (val from-list ((list (list#list (tuple comparable v)))) (dict#dict comparable v))
    (val map ((f (-> k a b)) (dict (dict#dict k a))) (dict#dict k b))
    (val foldl ((f (-> k v b b)) (z b) (list (dict#dict k v))) b)
    (val foldr ((f (-> k v b b)) (z b) (list (dict#dict k v))) b)
    (val filter ((f (-> comparable v basics#bool)) (dict (dict#dict comparable v))) (dict#dict comparable v))
    (val partition ((f (-> comparable v basics#bool)) (dict (dict#dict comparable v))) (tuple (dict#dict comparable v) (dict#dict comparable v)))
    (val union ((dict-1 (dict#dict comparable v)) (dict-2 (dict#dict comparable v))) (dict#dict comparable v))
    (val intersect ((dict-1 (dict#dict comparable v)) (dict-2 (dict#dict comparable v))) (dict#dict comparable v))
    (val diff ((dict-1 (dict#dict comparable v)) (dict-2 (dict#dict comparable v))) (dict#dict comparable v))
    (val merge ((left-only (-> comparable a result result)) (both (-> comparable a b result result)) (right-only (-> comparable b result result)) (dict-left (dict#dict comparable a)) (dict-right (dict#dict comparable b)) (input result)) result))
  (module set
    (type set (opaque) a)
    (val empty () (set#set a))
    (val singleton ((a comparable)) (set#set comparable))
    (val insert ((a comparable) (set (set#set comparable))) (set#set comparable))
    (val remove ((a comparable) (set (set#set comparable))) (set#set comparable))
    (val is-empty ((set (set#set comparable))) basics#bool)
    (val member ((a comparable) (set (set#set comparable))) basics#bool)
    (val size ((set (set#set comparable))) basics#int)
    (val to-list ((set (set#set a))) (list#list a))
    (val from-list ((list (list#list comparable))) (set#set comparable))
    (val map ((f (-> comparable comparable-2)) (set (set#set comparable))) (set#set comparable-2))
    (val foldl ((f (-> a b b)) (z b) (set (set#set a))) b)
    (val foldr ((f (-> a b b)) (z b) (set (set#set a))) b)
    (val filter ((f (-> comparable basics#bool)) (set (set#set comparable))) (set#set comparable))
    (val partition ((f (-> comparable basics#bool)) (set (set#set comparable))) (tuple (set#set comparable) (set#set comparable)))
    (val union ((set-1 (set#set comparable)) (set-2 (set#set comparable))) (set#set comparable))
    (val intersect ((set-1 (set#set comparable)) (set-2 (set#set comparable))) (set#set comparable))
    (val diff ((set-1 (set#set comparable)) (set-2 (set#set comparable))) (set#set comparable)))
  (module char
    (type char (opaque))
    (val is-upper ((c char#char)) basics#bool)
    (val is-lower ((c char#char)) basics#bool)
    (val is-alpha ((c char#char)) basics#bool)
    (val is-alpha-num ((c char#char)) basics#bool)
    (val is-digit ((c char#char)) basics#bool)
    (val is-oct-digit ((c char#char)) basics#bool)
    (val is-hex-digit ((c char#char)) basics#bool)
    (val to-upper ((c char#char)) char#char)
    (val to-lower ((c char#char)) char#char)
    (val to-locale-upper ((c char#char)) char#char)
    (val to-locale-lower ((c char#char)) char#char)
    (val to-code ((c char#char)) basics#int)
    (val from-code ((c basics#int)) char#char))
  (module int
    (type int-8 (opaque))
    (type int-16 (opaque))
    (type int-32 (opaque))
    (type int-64 (opaque))
    (val from-int-8 ((n int#int-8)) basics#int)
    (val to-int-8 ((n basics#int)) (maybe#maybe int#int-8))
    (val from-int-16 ((n int#int-16)) basics#int)
    (val to-int-16 ((n basics#int)) (maybe#maybe int#int-16))
    (val from-int-32 ((n int#int-32)) basics#int)
    (val to-int-32 ((n basics#int)) (maybe#maybe int#int-32))
    (val from-int-64 ((n int#int-64)) basics#int)
    (val to-int-64 ((n basics#int)) (maybe#maybe int#int-64)))
  (module decimal
    (type decimal (opaque))
    (val from-int ((n basics#int)) decimal#decimal)
    (val from-float ((f basics#float)) decimal#decimal)
    (val from-string ((str string#string)) (maybe#maybe decimal#decimal))
    (val hundred ((n basics#int)) decimal#decimal)
    (val thousand ((n basics#int)) decimal#decimal)
    (val million ((n basics#int)) decimal#decimal)
    (val tenth ((n basics#int)) decimal#decimal)
    (val hundredth ((n basics#int)) decimal#decimal)
    (val thousandth ((n basics#int)) decimal#decimal)
    (val millionth ((n basics#int)) decimal#decimal)
    (val bps ((n basics#int)) decimal#decimal)
    (val to-string ((decimal-value decimal#decimal)) string#string)
    (val to-float ((d decimal#decimal)) basics#float)
    (val add ((a decimal#decimal) (b decimal#decimal)) decimal#decimal)
    (val sub ((a decimal#decimal) (b decimal#decimal)) decimal#decimal)
    (val negate ((value decimal#decimal)) decimal#decimal)
    (val mul ((a decimal#decimal) (b decimal#decimal)) decimal#decimal)
    (val div ((a decimal#decimal) (b decimal#decimal)) (maybe#maybe decimal#decimal))
    (val div-with-default ((default decimal#decimal) (a decimal#decimal) (b decimal#decimal)) decimal#decimal)
    (val truncate ((d decimal#decimal)) decimal#decimal)
    (val round ((d decimal#decimal)) decimal#decimal)
    (val gt ((a decimal#decimal) (b decimal#decimal)) basics#bool)
    (val gte ((a decimal#decimal) (b decimal#decimal)) basics#bool)
    (val eq ((a decimal#decimal) (b decimal#decimal)) basics#bool)
    (val neq ((a decimal#decimal) (b decimal#decimal)) basics#bool)
    (val lt ((a decimal#decimal) (b decimal#decimal)) basics#bool)
    (val lte ((a decimal#decimal) (b decimal#decimal)) basics#bool)
    (val compare ((a decimal#decimal) (b decimal#decimal)) basics#order)
    (val abs ((value decimal#decimal)) decimal#decimal)
    (val shift-decimal-left ((n basics#int) (value decimal#decimal)) decimal#decimal)
    (val shift-decimal-right ((n basics#int) (value decimal#decimal)) decimal#decimal)
    (val zero () decimal#decimal)
    (val one () decimal#decimal)
    (val minus-one () decimal#decimal)))
