#!/usr/bin/env python3
"""Vendor pinned Morphir JSON cases and regenerate portable MoonBit tests.

Use --morphir PATH to refresh from a local clone; omit to regenerate from the
checked-in corpus. git show reads the pinned commit, regardless of checkout.
"""
import argparse
import json
import re
import subprocess
from pathlib import Path

ELM_PIN = "bc99af69a8b24d391311fae3822a87eafef3c334"
PIN = "5c5307d89f34d876e8f1ebf561ec55efbadf9fa0"
ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "pkgs/morphir-ir/conformance"
FILES = ["names", "types", "values", "patterns-and-literals", "definitions", "distributions", "versions"]


def refresh(source):
    def read(path):
        return subprocess.check_output(["git", "-C", str(source), "show", f"{PIN}:{path}"], text=True)
    cases = []
    for name in FILES:
        path = f"spec/ir/mck/{name}.md"
        for section in re.split(r"(?m)^## ", read(path))[1:]:
            header = section.splitlines()[0]
            metadata = dict(re.findall(r"(\w+)=([^ }]+)", header))
            if metadata.get("status") == "pending":
                continue
            fences = [{"role": role, "options": opts.strip(), "text": body.strip()}
                      for role, opts, body in re.findall(r"```json (canonical|accepted|rejected)([^\n]*)\n(.*?)\n```", section, re.S)]
            if fences:
                cases.append({"id": header.split(":")[0], "node": metadata["node"],
                              "version": int(metadata.get("version", 4)), "source": path, "fences": fences})
    (DEST / "fixtures/mck.json").write_text(json.dumps({"repository": "https://github.com/finos/morphir", "commit": PIN, "cases": cases}, indent=2) + "\n")
    (DEST / "fixtures/v3-greeting.json").write_text(read("spec/ir/mck/node-address-fixtures/v3-greeting.json"))
    for name in ["naming-conformance", "format-version-conformance"]:
        (DEST / f"fixtures/{name}.json").write_text(read(f"docs/spec/ir/fixtures/{name}.json"))


def refresh_elm(source):
    for version, suffix in [(1, "-v1"), (2, "")]:
        path = f"tests-integration/cli/test-data/rentals/expected-morphir-ir{suffix}.json"
        text = subprocess.check_output(["git", "-C", str(source), "show", f"{ELM_PIN}:{path}"], text=True)
        (DEST / f"fixtures/v{version}-rentals.json").write_text(text)



def codec(node, version):
    if node in ["Name", "Path", "FQName"]:
        suffix = {"Name": "name", "Path": "path", "FQName": "fqname"}[node]
        return f"@wire.read_{suffix}(INPUT)", f"@wire.write_{suffix}(VALUE)"
    if node == "FormatVersion":
        return "read_version(INPUT)", "@wire.write_version(VALUE)"
    prefix = f"@v{version}"
    if node == "Distribution":
        return f"{prefix}.from_json(INPUT)", f"{prefix}.to_json(VALUE)"
    if node.startswith("AccessControlled"):
        kind = "type_definition" if "Type" in node else "definition"
        return (f"{prefix}.read_access(INPUT, j => {prefix}.read_documented(j, {prefix}.read_{kind}))",
                f"{prefix}.write_access(VALUE, v => {prefix}.write_documented(v, {prefix}.write_{kind}))")
    suffix = {"ValueDefinition": "definition"}.get(node, re.sub(r"(?<!^)(?=[A-Z])", "_", node).lower())
    readargs = writeargs = ""
    if version == 3 and node not in ["Literal"]:
        readargs = ", read_unit"
        writeargs = ", write_unit"
        if node == "Value":
            readargs += ", read_unit"
            writeargs += ", write_unit"
    return f"{prefix}.read_{suffix}(INPUT{readargs})", f"{prefix}.write_{suffix}(VALUE{writeargs})"


def generate():
    corpus = json.loads((DEST / "fixtures/mck.json").read_text())
    lines = ["// Generated by scripts/refresh-ir-fixtures.py; do not edit.", "// Upstream JSON examples: FINOS, Apache-2.0."]
    for case in corpus["cases"]:
        rd, wr = codec(case["node"], case["version"])
        canonical = next((f["text"] for f in case["fences"] if f["role"] == "canonical"), None)
        for index, fence in enumerate(case["fences"]):
            lines.append(f'\n///|\ntest "{case["id"]} {index} {fence["role"]}" {{')
            expr = rd.replace("INPUT", "@wire.parse(" + json.dumps(fence["text"], ensure_ascii=False) + ")")
            if fence["role"] == "rejected" and "expect=" in fence["options"]:
                expected = dict(re.findall(r"(\w+)=([^ ]+)", fence["options"]))["expect"]
                lines.append(f"  let value = {expr}")
                lines.append(f'  assert_true(@wire.object({wr.replace("VALUE", "value")}).contains("{expected}"))')
            elif fence["role"] == "rejected":
                diagnostic = dict(re.findall(r"(\w+)=([^ ]+)", fence["options"]))["diagnostic"]
                lines.append(f'  let result = try {{ ignore({expr}); "accepted" }} catch {{ error => @wire.diagnostic(error) }}\n  assert_eq(result, "{diagnostic}")')
            else:
                lines.append(f"  let value = {expr}")
                if canonical and fence["role"] == "accepted":
                    expected = rd.replace("INPUT", "@wire.parse(" + json.dumps(canonical, ensure_ascii=False) + ")")
                    lines.append(f"  assert_eq(value, {expected})")
                encoded = wr.replace("VALUE", "value")
                lines.append(f"  let encoded = {encoded}")
                lines.append(f'  assert_eq({rd.replace("INPUT", "encoded")}, value)')
                if fence["role"] == "canonical":
                    # JSON tree equality ignores object ordering and whitespace.
                    lines.append('  assert_eq(encoded, @wire.parse(' + json.dumps(fence["text"], ensure_ascii=False) + '))')
            lines.append("}")
    (DEST / "mck_test.mbt").write_text("\n".join(lines) + "\n")
    greeting = (DEST / "fixtures/v3-greeting.json").read_text()
    (DEST / "greeting_test.mbt").write_text('// Generated by scripts/refresh-ir-fixtures.py.\n///|\nfn greeting() -> String {\n' + '  ' + json.dumps(greeting) + '\n}\n')
    for version in [1, 2]:
        source = json.loads((DEST / f"fixtures/v{version}-rentals.json").read_text())
        (DEST / f"rentals_v{version}_test.mbt").write_text('// Generated by scripts/refresh-ir-fixtures.py.\n///|\nfn rentals_v' + str(version) + '() -> String {\n  ' + json.dumps(json.dumps(source, separators=(",", ":"))) + '\n}\n')
    print(f"Generated {sum(len(c['fences']) for c in corpus['cases'])} JSON cases from {len(corpus['cases'])} upstream examples")


def generate_scalars():
    lines = ["// Generated by scripts/refresh-ir-fixtures.py."]
    corpus = json.loads((DEST / "fixtures/format-version-conformance.json").read_text())
    for c in corpus["scalarCases"]:
        source = json.dumps(json.dumps(c["value"], separators=(",", ":")))
        lines.append('\n///|\ntest ' + json.dumps("format: " + c["name"]) + ' {')
        if "diagnostic" in c["normalization"]:
            lines.append(f' let result = try {{ ignore(@wire.read_version(@wire.parse({source}))); "accepted" }} catch {{ error => @wire.diagnostic(error) }}')
            lines.append(' assert_eq(result, ' + json.dumps(c["normalization"]["diagnostic"]) + ')')
        else:
            lines.append(f' let version = @wire.read_version(@wire.parse({source}))')
            lines.append(' assert_eq(version.to_release_string(), ' + json.dumps(c["normalization"]["normalized"]) + ')')
            lines.append(' assert_eq(@wire.write_version(version), @wire.parse(' + json.dumps(json.dumps(c["normalization"]["canonical"])) + '))')
            expected = "supported" if c["value"] in [1, 2] else c["compatibility"]
            lines.append(' let result = try { version.check_supported(); "supported" } catch { error => @wire.diagnostic(error) }')
            lines.append(' assert_eq(result, ' + json.dumps(expected) + ')')
        lines.append('}')
    for c in corpus["rootDiagnosticCases"]:
        if c["format"] != "json":
            continue
        lines.append('\n///|\ntest ' + json.dumps(c["name"]) + ' {')
        lines.append(' let result = try { ignore(@any_json.read(' + json.dumps(c["source"]) + ')); "accepted" } catch { error => @wire.diagnostic(error) }')
        lines.append(' assert_eq(result, ' + json.dumps(c["diagnostic"]) + ')\n}')
    names = json.loads((DEST / "fixtures/naming-conformance.json").read_text())
    for index, c in enumerate(names["legacyDecodeCases"]):
        source = json.dumps(json.dumps(c["legacyArray"]))
        lines.append(f'\n///|\ntest "legacy name {index}" {{')
        lines.append(f' assert_eq(@wire.read_name(@wire.parse({source})).to_canonical(), ' + json.dumps(c["canonical"]["uppercase"]) + ')\n}')
    for index, c in enumerate(names["roundTripCases"]):
        text = c["canonical"]["uppercase"]
        source = json.dumps(json.dumps(text))
        lines.append(f'\n///|\ntest "canonical name {index}" {{')
        lines.append(f' assert_eq(@wire.read_name(@wire.parse({source})).to_canonical(), ' + json.dumps(text) + ')\n}')
    for index, c in enumerate(names["rejectCases"]):
        if c["validAs"]["uppercase"]:
            continue
        source = json.dumps(json.dumps(c["input"]))
        lines.append(f'\n///|\ntest "invalid name {index}" {{')
        lines.append(f' let result = try {{ ignore(@wire.read_name(@wire.parse({source}))); "accepted" }} catch {{ error => @wire.diagnostic(error) }}')
        lines.append(' assert_eq(result, "invalid_name")\n}')
    (DEST / "scalars_test.mbt").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--morphir", type=Path)
    parser.add_argument("--morphir-elm", type=Path)
    args = parser.parse_args()
    if args.morphir:
        refresh(args.morphir)
    if args.morphir_elm:
        refresh_elm(args.morphir_elm)
    generate()
    generate_scalars()
